export type OperatorRole = 'operator' | 'approver' | 'proposer' | 'client_member';
export type Screen = 'overview' | 'catalogue' | 'instances' | 'provisioning' | 'executions' | 'incidents' | 'certification' | 'releases' | 'deployments' | 'maintenance' | 'librarian' | 'audit-health';
export type ConsoleActor = { subject: string; roles: readonly OperatorRole[] };
export const screens: ReadonlyArray<{ id: Screen; title: string; summary: string }> = [
  { id: 'overview', title: 'Operations overview', summary: 'Current service health and operational attention.' }, { id: 'catalogue', title: 'Automation catalogue', summary: 'Approved package and release records.' }, { id: 'instances', title: 'Instance directory', summary: 'Managed instances and safe state controls.' }, { id: 'provisioning', title: 'Provisioning queue', summary: 'Provisioning jobs and recovery requests.' }, { id: 'executions', title: 'Execution explorer', summary: 'Redacted execution evidence and incident links.' }, { id: 'incidents', title: 'Incident centre', summary: 'Incident acknowledgement and recovery evidence.' }, { id: 'certification', title: 'Release certification', summary: 'Independent evaluation evidence and separate approval.' }, { id: 'releases', title: 'Certified releases', summary: 'Immutable certified release records; deployment operations are separate.' }, { id: 'deployments', title: 'Deployments', summary: 'Canary, promotion, and rollback for certified releases.' }, { id: 'maintenance', title: 'Maintenance', summary: 'Bounded, approved maintenance actions and findings.' }, { id: 'librarian', title: 'Librarian candidates', summary: 'Evidence-backed candidates, never direct production rewrites.' }, { id: 'audit-health', title: 'Audit and system health', summary: 'Auditable control and readiness records.' },
];
export function routeFor(hash: string): Screen { const route = hash.replace(/^#\/?/, '') as Screen; return screens.some((screen) => screen.id === route) ? route : 'overview'; }
export function allowed(actor: ConsoleActor) { return actor.roles.includes('operator') || actor.roles.includes('approver'); }
export function actionAvailability(actor: ConsoleActor, action: 'retry' | 'acknowledge' | 'resolve' | 'promote' | 'rollback' | 'pause' | 'resume' | 'canary' | 'approve' | 'reject' | 'supersede' | 'compensate') { if (!allowed(actor)) return { allowed: false, reason: 'Your Platform role is not authorised for operator actions.' }; if (['promote', 'approve'].includes(action) && !actor.roles.includes('approver')) return { allowed: false, reason: `${action === 'promote' ? 'Promotion' : 'Approval'} needs a separately authorised approver.` }; return { allowed: true, reason: 'A reason, confirmation, correlation, and resulting audit record are required.' }; }
