import type { ConsoleActor } from './console.js';

export type OperatorSession = { accessToken: string; subject: string; roles: ConsoleActor['roles'] };
export type OperatorRuntimeConfig = { productApiOrigin: string; oidcIssuer: string; oidcClientId: string; oidcRedirectUri: string; testMode: boolean };
type OidcMetadata = { authorization_endpoint: string; token_endpoint: string };
declare global { interface Window { LINKAUTOWORK_OPERATOR_SESSION?: OperatorSession } }
let accessToken: string | undefined;

/** Loads only public OIDC/API coordinates. Runtime configuration cannot contain credentials or tokens. */
export async function operatorRuntimeConfig(): Promise<OperatorRuntimeConfig> { const response = await fetch('/runtime-config.json', { cache: 'no-store' }); if (!response.ok) throw new Error('The operator sign-in configuration is unavailable.'); const value = await response.json() as Partial<OperatorRuntimeConfig>; return { productApiOrigin: value.productApiOrigin ?? '', oidcIssuer: value.oidcIssuer ?? '', oidcClientId: value.oidcClientId ?? '', oidcRedirectUri: value.oidcRedirectUri ?? '', testMode: value.testMode === true }; }
function random() { const bytes = new Uint8Array(32); crypto.getRandomValues(bytes); return btoa(String.fromCharCode(...bytes)).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, ''); }
async function challenge(verifier: string) { const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(verifier)); return btoa(String.fromCharCode(...new Uint8Array(digest))).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, ''); }
function claims(encodedJwt: string): Pick<OperatorSession, 'subject' | 'roles'> { try { const decoded = JSON.parse(atob(encodedJwt.split('.')[1].replace(/-/g, '+').replace(/_/g, '/'))) as { sub?: string; roles?: unknown }; const roles = Array.isArray(decoded.roles) ? decoded.roles.filter((role): role is ConsoleActor['roles'][number] => ['operator', 'approver', 'proposer', 'client_member'].includes(String(role) as ConsoleActor['roles'][number])) : []; return { subject: decoded.sub ?? '', roles }; } catch { return { subject: '', roles: [] }; } }
/** OIDC Authorization Code + PKCE. Display claims are advisory; Product API remains the authority. */
export async function operatorSession(config: OperatorRuntimeConfig): Promise<OperatorSession | undefined> { if (config.testMode && window.LINKAUTOWORK_OPERATOR_SESSION) return window.LINKAUTOWORK_OPERATOR_SESSION; if (accessToken) return { accessToken, ...claims(accessToken) }; const callback = new URL(location.href); const code = callback.searchParams.get('code'); const state = callback.searchParams.get('state'); if (!code || !state || state !== sessionStorage.getItem('linkautowork.operator.oidc.state') || !config.oidcIssuer || !config.oidcClientId || !config.oidcRedirectUri) return undefined; const verifier = sessionStorage.getItem('linkautowork.operator.oidc.verifier'); if (!verifier) return undefined; const metadata = await fetch(`${config.oidcIssuer.replace(/\/$/, '')}/.well-known/openid-configuration`, { cache: 'no-store' }).then(async (response) => { if (!response.ok) throw new Error('Platform sign-in metadata is unavailable.'); return response.json() as Promise<OidcMetadata>; }); const body = new URLSearchParams({ grant_type: 'authorization_code', code, redirect_uri: config.oidcRedirectUri, client_id: config.oidcClientId, code_verifier: verifier }); const token = await fetch(metadata.token_endpoint, { method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body }).then(async (response) => { if (!response.ok) throw new Error('Platform sign-in could not be completed.'); return response.json() as Promise<{ access_token?: string }>; }); if (!token.access_token) throw new Error('Platform sign-in did not return an access token.'); accessToken = token.access_token; sessionStorage.removeItem('linkautowork.operator.oidc.state'); sessionStorage.removeItem('linkautowork.operator.oidc.verifier'); callback.searchParams.delete('code'); callback.searchParams.delete('state'); history.replaceState({}, '', `${callback.pathname}${callback.search}${callback.hash}`); return { accessToken, ...claims(accessToken) }; }
/** Redirects to the Platform. The verifier/state are cleared after exchange; no token is persisted. */
export async function startOperatorSignIn(config: OperatorRuntimeConfig): Promise<void> { if (!config.oidcIssuer || !config.oidcClientId || !config.oidcRedirectUri) throw new Error('Platform operator sign-in has not been configured for this environment.'); const metadata = await fetch(`${config.oidcIssuer.replace(/\/$/, '')}/.well-known/openid-configuration`, { cache: 'no-store' }).then(async (response) => { if (!response.ok) throw new Error('Platform sign-in metadata is unavailable.'); return response.json() as Promise<OidcMetadata>; }); const state = random(); const verifier = random(); sessionStorage.setItem('linkautowork.operator.oidc.state', state); sessionStorage.setItem('linkautowork.operator.oidc.verifier', verifier); const query = new URLSearchParams({ response_type: 'code', client_id: config.oidcClientId, redirect_uri: config.oidcRedirectUri, scope: 'openid profile', state, code_challenge: await challenge(verifier), code_challenge_method: 'S256' }); location.assign(`${metadata.authorization_endpoint}?${query}`); }
