import type { SupabaseAuditClient } from '../../integrations/supabase-rpc.js';
import type { N8nClient } from '../../integrations/n8n-client.js';
import type { ActionAuthority, ActionExecutor, DeploymentAuthority, DeploymentExecutor, RetryDispatcher, RetryOutboxItem } from '../monitoring/operations-service.js';

/** Applies the n8n side of approved operations and compensates partial failures. */
export class N8nOperationsExecutor implements ActionExecutor, DeploymentExecutor, RetryDispatcher {
  constructor(private readonly n8n: N8nClient, private readonly store: SupabaseAuditClient) {}
  retry(orgId: string, instanceId: string, authority: ActionAuthority) { return this.store.callOperationsRpc<Record<string, unknown>>('linkautowork_execute_retry', { p_org_id: orgId, p_instance_id: instanceId, p_authorization_ref: authority.authorizationRef }); }
  async pause(orgId: string, instanceId: string, authority: ActionAuthority) { if (!authority.currentWorkflowId) throw new Error('current workflow is unavailable'); await this.n8n.setWorkflowActive(authority.currentWorkflowId, false); try { return await this.store.callOperationsRpc<Record<string, unknown>>('linkautowork_execute_instance_pause', { p_org_id: orgId, p_instance_id: instanceId, p_authorization_ref: authority.authorizationRef }); } catch (error) { await this.n8n.setWorkflowActive(authority.currentWorkflowId, true); throw error; } }
  async failover(orgId: string, instanceId: string, authority: ActionAuthority) { if (!authority.currentWorkflowId || !authority.baselineWorkflowId) throw new Error('failover workflows are unavailable'); await this.swap(authority.currentWorkflowId, authority.baselineWorkflowId); try { return await this.store.callOperationsRpc<Record<string, unknown>>('linkautowork_execute_failover', { p_org_id: orgId, p_instance_id: instanceId, p_authorization_ref: authority.authorizationRef }); } catch (error) { await this.swap(authority.baselineWorkflowId, authority.currentWorkflowId); throw error; } }
  async rollback(orgId: string, instanceId: string, authority: ActionAuthority) { if (!authority.currentWorkflowId || !authority.baselineWorkflowId) throw new Error('rollback workflows are unavailable'); await this.swap(authority.currentWorkflowId, authority.baselineWorkflowId); try { return await this.store.callOperationsRpc<Record<string, unknown>>('linkautowork_execute_rollback', { p_org_id: orgId, p_instance_id: instanceId, p_authorization_ref: authority.authorizationRef }); } catch (error) { await this.swap(authority.baselineWorkflowId, authority.currentWorkflowId); throw error; } }
  async apply(action: 'canary' | 'promote' | 'rollback', authority: DeploymentAuthority) { if (action === 'canary') { await this.n8n.setWorkflowActive(authority.candidateWorkflowId, true); return; } if (action === 'promote') { await this.swap(authority.baselineWorkflowId, authority.candidateWorkflowId); return; } await this.swap(authority.candidateWorkflowId, authority.baselineWorkflowId); }
  async compensate(action: 'canary' | 'promote' | 'rollback', authority: DeploymentAuthority) { if (action === 'canary') { await this.n8n.setWorkflowActive(authority.candidateWorkflowId, false); return; } if (action === 'promote') { await this.swap(authority.candidateWorkflowId, authority.baselineWorkflowId); return; } await this.swap(authority.baselineWorkflowId, authority.candidateWorkflowId); }
  async dispatch(item: RetryOutboxItem) { const result = await this.n8n.triggerWebhook(item.webhookPath, item.method, { retryOutboxId: item.id, instanceId: item.instanceId }); if (result.status < 200 || result.status >= 300) throw new Error(`retry delivery failed with status ${result.status}`); }
  private async swap(currentWorkflowId: string, targetWorkflowId: string) { await this.n8n.setWorkflowActive(targetWorkflowId, true); try { await this.n8n.setWorkflowActive(currentWorkflowId, false); } catch (error) { await this.n8n.setWorkflowActive(targetWorkflowId, false); await this.n8n.setWorkflowActive(currentWorkflowId, true); throw error; } }
}
