import { describe, expect, it } from 'vitest';
import { FakeProductAdapter, ProductError, beginSignup, renderPublicSite } from '../src/client-product.js';
import type { ClientIdentity, Provisioner, PublishedOffer } from '../src/contracts.js';

const orgA = '00000000-0000-0000-0000-000000000002'; const orgB = '00000000-0000-0000-0000-000000000003';
const offer: PublishedOffer = { productId: 'product-brief', offerId: 'brief-v2', releaseLabel: 'Briefing v2.0', name: 'Executive briefing', summary: 'A managed daily decision brief.', prerequisites: ['operator-assisted credentials'], pricePresentation: 'Pricing is confirmed with support before activation.', supportPath: 'support@linktrend.example', published: true, fields: [{ key: ('timezone'), label: 'Time zone', kind: 'select', required: true, options: ['Asia/Taipei', 'UTC'] }] };
const privateOffer: PublishedOffer = { ...offer, offerId: 'internal', name: 'Internal workflow', published: false };
class FakeProvisioner implements Provisioner { calls = 0; fail = false; async provision(input: { idempotencyKey: string }) { this.calls++; if (this.fail) throw new Error('internal detail'); return { instanceId: `instance-${input.idempotencyKey}` }; } }
const identity = (organisationId = orgA): ClientIdentity => ({ subject: 'client-user', organisationId, roles: ['client_admin'] });
function setup(user: ClientIdentity | undefined = identity()) { const provisioner = new FakeProvisioner(); return { provisioner, adapter: new FakeProductAdapter(user, [offer, privateOffer], provisioner) }; }

describe('WP-11 client product', () => {
  it('renders only curated published offers and never internal automation assets', async () => { const { adapter } = setup(); const html = await renderPublicSite(adapter); expect(html).toContain('Executive briefing'); expect(html).not.toMatch(/Internal workflow|n8n|workflow JSON|secret/i); expect(html).toContain('aria-label'); });
  it('requires trusted authentication, fixes offer identity and makes duplicate signup idempotent', async () => { const unauthenticated = new FakeProductAdapter(undefined, [offer, privateOffer], new FakeProvisioner()); await expect(beginSignup(unauthenticated, { offerId: offer.offerId, termsVersion: 'terms-2026-08', idempotencyKey: 'signup-one', paymentRequired: true })).rejects.toMatchObject({ code: 'unauthenticated' }); const { adapter } = setup(); const input = { offerId: offer.offerId, termsVersion: 'terms-2026-08', idempotencyKey: 'signup-one', paymentRequired: true }; const first = await beginSignup(adapter, input); const again = await beginSignup(adapter, input); expect(again.id).toBe(first.id); expect(first.state).toBe('awaiting_payment'); await expect(beginSignup(adapter, { ...input, offerId: 'internal', idempotencyKey: 'signup-two' })).rejects.toMatchObject({ code: 'validation_failed' }); });
  it('handles fake payment replay and out-of-order messages without duplicating an order', async () => { const { adapter } = setup(); const order = await beginSignup(adapter, { offerId: offer.offerId, termsVersion: 'terms-2026-08', idempotencyKey: 'signup-pay', paymentRequired: true }); const sig = adapter.signPayment('event-1', order.id, 'payment.succeeded'); expect((await adapter.paymentEvent({ eventId: 'event-1', orderId: order.id, type: 'payment.succeeded', signature: sig })).state).toBe('awaiting_configuration'); expect((await adapter.paymentEvent({ eventId: 'event-1', orderId: order.id, type: 'payment.succeeded', signature: sig })).state).toBe('awaiting_configuration'); const later = adapter.signPayment('event-2', order.id, 'payment.failed'); expect((await adapter.paymentEvent({ eventId: 'event-2', orderId: order.id, type: 'payment.failed', signature: later })).state).toBe('awaiting_configuration'); });
  it('separates settings from credential intake and provisions exactly one isolated instance after the assisted gate', async () => { const { adapter, provisioner } = setup(); const order = await beginSignup(adapter, { offerId: offer.offerId, termsVersion: 'terms-2026-08', idempotencyKey: 'signup-free', paymentRequired: false }); expect((await adapter.getOrder(order.id, identity())).state).toBe('awaiting_configuration'); await adapter.saveSettings(order.id, identity(), { timezone: 'Asia/Taipei' }); expect((await adapter.provision(order.id, identity())).state).toBe('credentials_required'); expect((await adapter.provision(order.id, identity())).state).toBe('active'); expect(provisioner.calls).toBe(1); await expect(adapter.saveSettings(order.id, identity(), { credential: 'never' })).rejects.toBeInstanceOf(ProductError); });
  it('keeps portal and direct action URLs organisation-scoped, redacts failures, and supports only approved actions', async () => { const { adapter, provisioner } = setup(); const order = await beginSignup(adapter, { offerId: offer.offerId, termsVersion: 'terms', idempotencyKey: 'signup-fail', paymentRequired: false }); expect((await adapter.provision(order.id, identity())).state).toBe('credentials_required'); provisioner.fail = true; await expect(adapter.provision(order.id, identity())).rejects.toMatchObject({ code: 'provisioning_failed' }); expect((await adapter.getOrder(order.id, identity())).failureCode).toBe('provisioning_failed'); expect(await adapter.portal(identity(orgB))).toEqual([]); await expect(adapter.action({ identity: identity(orgB), instanceId: 'instance-missing', action: 'pause', idempotencyKey: 'cross-org-action' })).rejects.toMatchObject({ code: 'not_found' }); });
});
