import { createHmac } from 'node:crypto';
import { createServer } from 'node:http';
import type { AddressInfo } from 'node:net';
import request from 'supertest';
import { afterEach, describe, expect, it } from 'vitest';
import { createProductApi } from '../../product-api/src/app.js';
import { InMemoryProductApiService } from '../../product-api/src/service.js';
import { ProductApiHttpAdapter } from '../src/product-api-http.js';

const secret = 'ltfx.ph.f36664c531.v1'; const issuer = 'https://platform.test'; const audience = 'linkautowork-product-api'; const orgA = '00000000-0000-0000-0000-000000000002'; const orgB = '00000000-0000-0000-0000-000000000003';
function token(orgId: string) { const header = Buffer.from(JSON.stringify({ alg: 'HS256', typ: 'JWT' })).toString('base64url'); const payload = Buffer.from(JSON.stringify({ iss: issuer, aud: audience, sub: `client-${orgId.at(-1)}`, org_id: orgId, roles: ['client_admin'], exp: Math.floor(Date.now() / 1000) + 60 })).toString('base64url'); return `${header}.${payload}.${createHmac('sha256', secret).update(`${header}.${payload}`).digest('base64url')}`; }
function fixture() { const service = new InMemoryProductApiService([{ id: 'briefing', name: 'Executive briefing', summary: 'A managed decision brief.', version: 2, signupPrerequisites: ['operator-assisted configuration'] }], [{ id: 'instance-a', orgId: orgA, state: 'active', configurationStatus: 'operator_assisted_required', deploymentStatus: 'active', health: 'healthy', executions: [{ id: 'run-1', status: 'succeeded' }], incidents: [], approvedOutputs: [], supportRequests: [] }, { id: 'instance-b', orgId: orgB, state: 'active', configurationStatus: 'operator_assisted_required', deploymentStatus: 'active', health: 'healthy', executions: [], incidents: [], approvedOutputs: [], supportRequests: [] }]); return { service, app: createProductApi({ nodeEnv: 'test', issuer, audience, testJwtSecret: secret, webhookSecret: 'ltfx.ph.38abc48c1e.v1' }, service) }; }
const servers: Array<ReturnType<typeof createServer>> = [];
afterEach(async () => { await Promise.all(servers.splice(0).map((server) => new Promise<void>((resolve) => server.close(() => resolve())))); });
async function adapterFor(app: ReturnType<typeof fixture>['app'], orgId = orgA) { const server = createServer(app); servers.push(server); await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve)); const address = server.address() as AddressInfo; return new ProductApiHttpAdapter(`http://127.0.0.1:${address.port}`, async () => ({ accessToken: token(orgId), subject: 'client-user', organisationId: orgId, roles: ['client_admin'] })); }

describe('WP-11 HTTP adapter against the WP-09 Product API', () => {
  it('uses the production-shaped bearer contract for a specific offer through order, subscription, safe configuration, provisioning, and portal status', async () => { const { app } = fixture(); const adapter = await adapterFor(app); expect(await adapter.signupPrerequisites()).toEqual({ configuration: 'operator_assisted_required', credentialIntake: 'not_available' }); const [offer] = await adapter.publishedOffers(); expect(offer).toMatchObject({ productId: 'briefing', offerId: 'briefing', releaseLabel: 'Offer v2' }); const order = await adapter.createOrder({ productId: offer.productId, idempotencyKey: 'client-order-key' }); expect(order.status).toBe('pending_operator_review'); expect((await adapter.createOrder({ productId: offer.productId, idempotencyKey: 'client-order-key' })).id).toBe(order.id); const subscription = await adapter.createSubscription({ orderId: order.id, idempotencyKey: 'client-subscription-key' }); expect(subscription.status).toBe('pending_provisioning'); expect((await adapter.submitConfiguration({ subscriptionId: subscription.id, values: { timezone: 'Asia/Taipei' }, idempotencyKey: 'client-configuration-key' })).status).toBe('operator_assisted_required'); expect((await adapter.requestProvisioning({ subscriptionId: subscription.id, idempotencyKey: 'client-provisioning-key' })).status).toBe('requested'); const portal = await adapter.portal(); expect(portal.instances.items.map((item) => item.id)).toEqual(['instance-a']); expect(portal.configuration.items).toEqual(expect.arrayContaining([expect.objectContaining({ status: 'operator_assisted_required' })])); expect(portal.provisioning.items).toEqual(expect.arrayContaining([expect.objectContaining({ status: 'requested' })])); expect(portal.orders.items).toEqual([expect.objectContaining({ id: order.id })]); expect(portal.subscriptions.items).toEqual([expect.objectContaining({ id: subscription.id })]); });
  it('keeps actions and support organisation scoped and rejects credential-shaped configuration', async () => { const { app } = fixture(); const adapterA = await adapterFor(app, orgA); const adapterB = await adapterFor(app, orgB); const order = await adapterA.createOrder({ productId: 'briefing', idempotencyKey: 'scoped-order-key' }); const subscription = await adapterA.createSubscription({ orderId: order.id, idempotencyKey: 'scoped-subscription-key' }); expect((await adapterA.instanceAction({ instanceId: 'instance-a', action: 'pause', reason: 'Client maintenance window', idempotencyKey: 'pause-instance-key' })).state).toBe('paused'); await expect(adapterB.instanceAction({ instanceId: 'instance-a', action: 'pause', reason: 'Cross tenant attempt', idempotencyKey: 'cross-tenant-key' })).rejects.toMatchObject({ code: 'not_found', status: 404 }); await expect(adapterA.submitConfiguration({ subscriptionId: subscription.id, values: { apiKey: 'ltfx.app.test.ts.apikey.18.2.v1' }, idempotencyKey: 'credential-input-key' })).rejects.toMatchObject({ code: 'validation_failed', status: 400 }); expect((await adapterA.createSupportRequest({ subject: 'Configuration assistance', message: 'Please arrange the approved credential process.', idempotencyKey: 'support-request-key' })).status).toBe('open'); expect((await adapterB.portal()).supportRequests.items).toEqual([]); expect(Object.getOwnPropertyNames(ProductApiHttpAdapter.prototype)).not.toContain('submitCredentials'); });
  it('proves signed ordered payment webhook replay handling against the same local Product API service', async () => { const { app } = fixture(); const event = { eventId: 'payment-event-1', eventType: 'payment.succeeded', occurredAt: new Date().toISOString(), providerSequence: 10, orgId: orgA, subscriptionId: '10000000-0000-0000-0000-000000000001' }; const signature = createHmac('sha256', 'webhook-secret').update(JSON.stringify(event)).digest('hex'); expect((await request(app).post('/v1/webhooks/status').set('x-link-webhook-signature', signature).send(event)).body).toMatchObject({ accepted: true, replay: false, state: 'awaiting_configuration', providerSequence: 10 }); expect((await request(app).post('/v1/webhooks/status').set('x-link-webhook-signature', signature).send(event)).body).toMatchObject({ accepted: true, replay: true }); });
});
