import { ProductApiHttpAdapter, ProductApiHttpError } from './product-api-http.js';
import { beginPlatformSignIn, browserRuntimeConfig, platformSession } from './platform-auth.js';
const escape = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character] ?? character);
const key = () => crypto.randomUUID();
type SignupIntent = { productId: string; orderKey: string; subscriptionKey: string; configurationKey: string; provisioningKey: string; orderId?: string; subscriptionId?: string; instanceId?: string };
const intentKey = (productId: string) => `linkautowork.signup.${productId}`;
function savedIntent(productId: string): SignupIntent { try { const existing = localStorage.getItem(intentKey(productId)); if (existing) return JSON.parse(existing) as SignupIntent; } catch { /* a disabled browser store only removes refresh reuse, never changes server idempotency */ } const created = { productId, orderKey: key(), subscriptionKey: key(), configurationKey: key(), provisioningKey: key() }; try { localStorage.setItem(intentKey(productId), JSON.stringify(created)); } catch { /* see above */ } return created; }
function saveIntent(intent: SignupIntent) { try { localStorage.setItem(intentKey(intent.productId), JSON.stringify(intent)); } catch { /* see above */ } }
async function adapter() { const config = await browserRuntimeConfig(); return { config, client: new ProductApiHttpAdapter(config.productApiOrigin, () => platformSession(config)) }; }
function problem(error: unknown) { return error instanceof ProductApiHttpError || error instanceof Error ? error.message : 'The request could not be completed. No credentials were stored.'; }
async function render() {
  const root = document.querySelector('#app'); if (!root) return; const { config, client } = await adapter();
  try { const offers = await client.publishedOffers(); const session = await client.currentIdentity(); root.innerHTML = `<header><a class="brand" href="/">LiNKautowork</a><span>${session ? 'Signed in through LiNKplatform' : 'Browse managed automations'}</span></header><main><h1>Hosted automations, operated for you</h1><p>Choose a published service. Configuration is safe and ordinary; credential onboarding is always assisted by an operator.</p><section aria-label="Published managed automations">${offers.map((offer) => `<article><h2>${escape(offer.name)}</h2><p>${escape(offer.summary)}</p><p>${escape(offer.pricePresentation)}</p><button data-product="${escape(offer.productId)}" ${session ? '' : 'disabled'}>Request this automation</button></article>`).join('') || '<p>No published automation is currently available.</p>'}</section><section aria-live="polite" id="status"></section>${session ? '<section id="portal" aria-label="Your automation instances">Loading your managed automations…</section>' : '<p>Sign in through LiNKplatform to request or manage an automation.</p><button type="button" data-sign-in>Sign in through LiNKplatform</button>'}</main>`; if (!session) { root.querySelector<HTMLButtonElement>('[data-sign-in]')?.addEventListener('click', () => { void beginPlatformSignIn(config).catch((error) => { const status = root.querySelector('#status'); if (status) status.textContent = problem(error); }); }); return; } const portal = await client.portal(); const panel = root.querySelector('#portal'); if (panel) panel.innerHTML = `<h2>Your managed automations</h2><ul>${portal.instances.items.map((instance) => `<li><strong>${escape(instance.id)}</strong> — ${escape(instance.state)} / ${escape(instance.health)} <button data-pause="${escape(instance.id)}">${instance.state === 'paused' ? 'Resume' : 'Pause'}</button></li>`).join('') || '<li>No active instance yet. Requests appear here after operator provisioning.</li>'}</ul><p>Provisioning requests: ${portal.provisioning.items.length}. Credential values are never accepted in this portal.</p>`;
    root.querySelectorAll<HTMLButtonElement>('[data-product]').forEach((button) => button.addEventListener('click', async () => { const status = root.querySelector('#status'); button.disabled = true; try { const selected = offers.find((offer) => offer.productId === (button.dataset.product ?? '')); if (!selected?.terms) throw new Error('This published offer has no authoritative terms metadata.'); const intent = savedIntent(button.dataset.product ?? ''); const order = intent.orderId ? { id: intent.orderId } : await client.createOrder({ productId: intent.productId, idempotencyKey: intent.orderKey }); intent.orderId = order.id; saveIntent(intent); await client.acceptTerms({ orderId: order.id, termsDocumentId: selected.terms.documentId, termsVersion: selected.terms.version, termsDigest: selected.terms.digest }); const subscription = intent.subscriptionId ? { id: intent.subscriptionId } : await client.createSubscription({ orderId: order.id, idempotencyKey: intent.subscriptionKey }); intent.subscriptionId = subscription.id; saveIntent(intent); await client.submitConfiguration({ subscriptionId: subscription.id, values: { timezone: 'Asia/Taipei' }, idempotencyKey: intent.configurationKey }); await client.requestProvisioning({ subscriptionId: subscription.id, idempotencyKey: intent.provisioningKey }); if (status) status.textContent = 'Your request was recorded. An operator will complete safe configuration, credential onboarding, and provisioning.'; } catch (error) { if (status) status.textContent = problem(error); } finally { button.disabled = false; } }));
    root.querySelectorAll<HTMLButtonElement>('[data-pause]').forEach((button) => button.addEventListener('click', async () => { const status = root.querySelector('#status'); try { await client.instanceAction({ instanceId: button.dataset.pause ?? '', action: button.textContent === 'Resume' ? 'resume' : 'pause', reason: 'Requested in client portal', idempotencyKey: key() }); await render(); } catch (error) { if (status) status.textContent = problem(error); } }));
  } catch (error) { root.innerHTML = `<main><h1>Service temporarily unavailable</h1><p role="alert">${escape(problem(error))}</p><p>Please retry later or contact support. No automation request was made.</p></main>`; }
}
addEventListener('DOMContentLoaded', () => { void render(); });
