import { createHmac, timingSafeEqual } from 'node:crypto';
import type { ClientIdentity, ClientOrder, OrderState, PortalInstance, ProductClientAdapter, Provisioner, PublishedOffer } from './contracts.js';

const transitions: Readonly<Record<OrderState, readonly OrderState[]>> = { initiated: ['awaiting_payment', 'payment_not_required'], awaiting_payment: ['paid', 'failed'], payment_not_required: ['awaiting_configuration'], paid: ['awaiting_configuration'], awaiting_configuration: ['credentials_required', 'provisioning', 'cancel_requested'], credentials_required: ['provisioning', 'cancel_requested'], provisioning: ['active', 'failed'], active: ['suspended', 'cancel_requested'], suspended: ['active', 'cancel_requested'], cancel_requested: ['cancelled'], cancelled: [], failed: [] };
const banned = /(?:credential|secret|password|token|api[_-]?key)/i;
function requireIdentity(identity: ClientIdentity | undefined): asserts identity is ClientIdentity { if (!identity) throw new ProductError('unauthenticated', 'Sign in with LiNKplatform to continue.'); }
function sameOrg(order: ClientOrder, identity: ClientIdentity) { if (order.organisationId !== identity.organisationId) throw new ProductError('not_found', 'The requested item is unavailable.'); }
function move(order: ClientOrder, next: OrderState) { if (!transitions[order.state].includes(next)) throw new ProductError('invalid_transition', 'This request is not available in the current state.'); order.state = next; }
function escape(value: string) { return value.replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char] ?? char); }
export class ProductError extends Error { constructor(readonly code: string, message: string) { super(message); } }

/** Local, deterministic adapter. Production must replace it with the frozen WP-09-authenticated service contract. */
export class FakeProductAdapter implements ProductClientAdapter {
  readonly orders = new Map<string, ClientOrder>(); readonly instances = new Map<string, PortalInstance>(); private readonly paymentEvents = new Set<string>(); private readonly requests = new Map<string, string>();
  constructor(private identity: ClientIdentity | undefined, private readonly offers: PublishedOffer[], private readonly provisioner: Provisioner, private readonly webhookSecret = 'local-fake-payment-secret') {}
  async currentIdentity() { return this.identity; }
  async publishedOffers() { return this.offers.filter((offer) => offer.published); }
  async createOrder(input: { organisationId: string; offerId: string; termsVersion: string; idempotencyKey: string; paymentRequired: boolean }) {
    requireIdentity(this.identity); if (this.identity.organisationId !== input.organisationId) throw new ProductError('forbidden', 'Organisation selection must come from your signed identity.');
    const existing = this.requests.get(input.idempotencyKey); if (existing) return this.orders.get(existing)!;
    const offer = this.offers.find((candidate) => candidate.published && candidate.offerId === input.offerId); if (!offer || !input.termsVersion.trim()) throw new ProductError('validation_failed', 'Choose a published offer and accept the current terms.');
    const order: ClientOrder = { id: `order-${this.orders.size + 1}`, organisationId: input.organisationId, offerId: offer.offerId, acceptedTermsVersion: input.termsVersion, state: 'initiated', settings: {} }; move(order, input.paymentRequired ? 'awaiting_payment' : 'payment_not_required');
    // Free/approved offers still record the commercial gate before configuration may begin.
    if (!input.paymentRequired) move(order, 'awaiting_configuration'); this.orders.set(order.id, order); this.requests.set(input.idempotencyKey, order.id); return order;
  }
  async getOrder(id: string, identity: ClientIdentity) { const order = this.orders.get(id); if (!order) throw new ProductError('not_found', 'The requested order is unavailable.'); sameOrg(order, identity); return order; }
  async saveSettings(id: string, identity: ClientIdentity, settings: Record<string, string>) { const order = await this.getOrder(id, identity); if (!['awaiting_configuration', 'credentials_required'].includes(order.state)) throw new ProductError('invalid_transition', 'Configuration is not ready.'); const offer = this.offers.find((candidate) => candidate.offerId === order.offerId)!;
    for (const field of offer.fields) { if (banned.test(field.key) || banned.test(field.label)) throw new ProductError('unsafe_schema', 'Credential fields require operator-assisted onboarding.'); if (field.required && !settings[field.key]?.trim()) throw new ProductError('validation_failed', `Complete ${field.label}.`); if (field.kind === 'select' && settings[field.key] && !field.options?.includes(settings[field.key])) throw new ProductError('validation_failed', `Choose a supported ${field.label}.`); }
    for (const key of Object.keys(settings)) if (!offer.fields.some((field) => field.key === key) || banned.test(key)) throw new ProductError('validation_failed', 'Only published non-secret settings can be saved.'); order.settings = { ...settings }; return order;
  }
  async paymentEvent(input: { eventId: string; orderId: string; type: 'payment.succeeded' | 'payment.failed'; signature: string }) { const expected = createHmac('sha256', this.webhookSecret).update(`${input.eventId}:${input.orderId}:${input.type}`).digest('hex'); const supplied = Buffer.from(input.signature); if (supplied.length !== expected.length || !timingSafeEqual(supplied, Buffer.from(expected))) throw new ProductError('invalid_webhook', 'Payment status could not be verified.'); const order = this.orders.get(input.orderId); if (!order) throw new ProductError('not_found', 'Payment order is unavailable.'); if (this.paymentEvents.has(input.eventId)) return order; this.paymentEvents.add(input.eventId); if (order.state !== 'awaiting_payment') return order; if (input.type === 'payment.failed') { move(order, 'failed'); order.failureCode = 'payment_failed'; return order; } move(order, 'paid'); move(order, 'awaiting_configuration'); return order; }
  async provision(id: string, identity: ClientIdentity) { const order = await this.getOrder(id, identity); if (!['awaiting_configuration', 'credentials_required'].includes(order.state)) throw new ProductError('invalid_transition', 'Provisioning is not ready.'); const offer = this.offers.find((candidate) => candidate.offerId === order.offerId)!; if (offer.prerequisites.includes('operator-assisted credentials') && order.state !== 'credentials_required') { move(order, 'credentials_required'); return order; } move(order, 'provisioning'); try { const result = await this.provisioner.provision({ idempotencyKey: `provision:${order.id}`, organisationId: order.organisationId, offerId: order.offerId }); order.instanceId = result.instanceId; this.instances.set(result.instanceId, { id: result.instanceId, organisationId: order.organisationId, productName: offer.name, releaseLabel: offer.releaseLabel, state: 'active', configurationStatus: offer.prerequisites.includes('operator-assisted credentials') ? 'credentials_required' : 'complete', health: 'healthy', recentRuns: [], incidents: [], approvedOutputs: [] }); move(order, 'active'); return order; } catch { order.failureCode = 'provisioning_failed'; move(order, 'failed'); throw new ProductError('provisioning_failed', 'Provisioning could not be completed. Our support team has been notified.'); } }
  async portal(identity: ClientIdentity) { return [...this.instances.values()].filter((item) => item.organisationId === identity.organisationId); }
  async action(input: { identity: ClientIdentity; instanceId: string; action: 'pause' | 'resume' | 'retry'; idempotencyKey: string }) { const request = this.requests.get(input.idempotencyKey); if (request) return this.instances.get(request)!; const item = this.instances.get(input.instanceId); if (!item || item.organisationId !== input.identity.organisationId) throw new ProductError('not_found', 'The requested instance is unavailable.'); if (input.action === 'pause' && item.state === 'active') item.state = 'paused'; if (input.action === 'resume' && item.state === 'paused') item.state = 'active'; if (input.action === 'retry' && item.state !== 'failed') throw new ProductError('invalid_action', 'Only eligible failed runs may be retried.'); this.requests.set(input.idempotencyKey, item.id); return item; }
  signPayment(eventId: string, orderId: string, type: 'payment.succeeded' | 'payment.failed') { return createHmac('sha256', this.webhookSecret).update(`${eventId}:${orderId}:${type}`).digest('hex'); }
}

/** Renders only curated public offer content; no internal automation asset is included in the output. */
export async function renderPublicSite(adapter: ProductClientAdapter) { const offers = await adapter.publishedOffers(); return `<main><h1>Managed automation outcomes</h1><p>LiNKtrend operates selected automations for your organisation. Support is available before and after activation.</p><section aria-label="Published products">${offers.map((offer) => `<article><h2>${escape(offer.name)}</h2><p>${escape(offer.summary)}</p><p>Release: ${escape(offer.releaseLabel)}</p><p>${escape(offer.pricePresentation)}</p><a href="/signup/${encodeURIComponent(offer.offerId)}">Choose this product</a></article>`).join('')}</section></main>`; }
export async function beginSignup(adapter: ProductClientAdapter, input: { offerId: string; termsVersion: string; idempotencyKey: string; paymentRequired: boolean }) { const identity = await adapter.currentIdentity(); requireIdentity(identity); return adapter.createOrder({ organisationId: identity.organisationId, ...input }); }
