import fs from 'node:fs'; import path from 'node:path'; import {createHmac,generateKeyPairSync,sign} from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { librarianAutomationRequestSchema } from '../src/contracts/librarian-automation.js';
import { AutomationLibrarianService, DurableMemoryLibrarianStore, GovernedReceiptVerifierKeys, Wp02PackageValidator, Wp06ReceiptEvaluator, sha256, type CandidateValidator, type EvidenceResolver, type ResolvedEvidence } from '../src/services/librarian/automation-librarian.js';
import { validateWp02Package } from '../src/services/librarian/wp02-runtime.js';
import { RemoteInstitutionalJwksProvider, requireLibrarianInstitutionalClaim, type InstitutionalJwk, type InstitutionalJwksProvider } from '../src/middleware/auth.js'; import type { AppEnv } from '../src/config/env.js';
import { SupabaseAuditClient } from '../src/integrations/supabase-rpc.js';

const orgId='00000000-0000-0000-0000-000000000001', otherOrgId='00000000-0000-0000-0000-000000000002', releaseId='20000000-0000-0000-0000-000000000001';
const patchDigest='sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc';
const verifierKey='wp06-disposable-verifier-key-material'; const verifierKeyId='injected-eval-verifier-v1',verifierKeyRef=`gsm://linkautowork/eval-receipt-verifier/${verifierKeyId}`;
const validReceipt=()=>{ const receipt={schemaVersion:'0.2',automationId:'urgent-intake',automationVersion:'1.0.0',packageDigest:patchDigest,verdict:'passed'}; return {receipt,verifier:{algorithm:'hmac-sha256',keyId:verifierKeyId,signature:createHmac('sha256',verifierKey).update(JSON.stringify(receipt,Object.keys(receipt).sort())).digest('hex')}}; };
const evidence=(overrides:Partial<ResolvedEvidence>={}):ResolvedEvidence=>{ const payload=overrides.payload??validReceipt(); return {ref:'evidence://eval/one',payload,hash:sha256(payload),orgId,verifierKeyId,verifierKeyRef,...overrides}; };
class MapResolver implements EvidenceResolver { constructor(private readonly values:ResolvedEvidence[]){} async resolve(ref:string){return this.values.find((item)=>item.ref===ref);} }
const validator:CandidateValidator={validate:async()=>({passed:true,evidenceRef:'evidence://wp02/pass'})};
const makeRequest=(values:ResolvedEvidence[],changes:Record<string,unknown>={})=>librarianAutomationRequestSchema.parse({domain:'automation',orgId,source:{automationId:'urgent-intake',version:'1.0.0',releaseId},trigger:'repeated_deterministic_failure',evidence:values.map((item,index)=>({ref:item.ref,hash:item.hash,kind:index===0?'eval_receipt':'execution_projection',...(item.orgId?{orgId:item.orgId}:{aggregateApprovalRef:item.aggregateApproval?.approvalRef})})),proposal:{opportunityClass:'reliability',scope:'Bound retry handling to deterministic upstream timeout failures.',patch:{artifactRef:'candidate://urgent-intake/retry-v2',digest:patchDigest},packagePath:'automations/packages/_golden-template',expectedBenefit:'Fewer timeout failures.',riskLevel:'low',requiredEvalSuites:['regression']},actor:{id:'librarian:automation',kind:'librarian'},model:{provider:'test',model:'deterministic',version:'1'},policyVersion:'automation-librarian-policy-v1',promptVersion:'automation-librarian-prompt-v1',toolActivity:['evidence_read','validator','eval_runner'],...changes});
const values=()=>[evidence(),evidence({ref:'evidence://execution/two',payload:{status:'failed',sequence:2}})];
const service=(items=values(),store=new DurableMemoryLibrarianStore(),v:CandidateValidator=validator)=>new AutomationLibrarianService(store,new MapResolver(items),v,new Wp06ReceiptEvaluator(new GovernedReceiptVerifierKeys(new Map([[verifierKeyId,verifierKey]]))),new Set(['institutional-aggregate-authority']));
const librarianJwt=(secret:string,claims:Record<string,unknown>)=>{const header=Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url'),body=Buffer.from(JSON.stringify(claims)).toString('base64url'),signature=createHmac('sha256',secret).update(`${header}.${body}`).digest('base64url');return `${header}.${body}.${signature}`;};
const institutionalEnv=(secret:ltfx.ph.a8b3fb7710.v1,LIBRARIAN_JWT_TEST_SECRET:secret,LIBRARIAN_JWT_ISSUER:'https://librarian.test.linktrend.local',LIBRARIAN_JWT_AUDIENCE:'linkautowork-librarian'} as AppEnv);
const institutionalClaim=(token:string,env:AppEnv)=>{const request={header:(name:string)=>name==='x-librarian-institutional-token'?token:undefined} as never;let error:unknown;requireLibrarianInstitutionalClaim(env)(request,{} as never,(value?:unknown)=>{error=value;});return {request:request as {librarianInstitutional?:unknown},error};};
const rsa=generateKeyPairSync('rsa',{modulusLength:2048}),rotatedRsa=generateKeyPairSync('rsa',{modulusLength:2048});
const rsJwt=(privateKey:typeof rsa.privateKey,kid:string,claims:Record<string,unknown>,alg='RS256')=>{const header=Buffer.from(JSON.stringify({alg,typ:'JWT',kid})).toString('base64url'),body=Buffer.from(JSON.stringify(claims)).toString('base64url'),signature=sign('RSA-SHA256',Buffer.from(`${header}.${body}`),privateKey).toString('base64url');return `${header}.${body}.${signature}`;};
class FakeJwks implements InstitutionalJwksProvider{unavailable=false;keys=new Map<string,InstitutionalJwk>([['key-1',{...rsa.publicKey.export({format:'jwk'}),kid:'key-1',use:'sig'}]]);calls=0;async get(kid:string){this.calls++;if(this.unavailable)throw new Error('offline');return this.keys.get(kid);}}
const productionEnv=()=>({NODE_ENV:'production',LIBRARIAN_JWT_ISSUER:'https://librarian.example.test',LIBRARIAN_JWT_AUDIENCE:'linkautowork-librarian',LIBRARIAN_JWKS_CACHE_TTL_SECONDS:60} as AppEnv);
const institutionalClaimAsync=(token:string,env:AppEnv,provider:InstitutionalJwksProvider)=>new Promise<{claim?:unknown;error?:unknown}>((resolve)=>{const request={header:(name:string)=>name==='x-librarian-institutional-token'?token:undefined,platformInvocation:{orgId,service:'librarian',subject:'platform'}} as never;requireLibrarianInstitutionalClaim(env,provider)(request,{} as never,(error?:unknown)=>resolve({claim:(request as {librarianInstitutional?:unknown}).librarianInstitutional,error}));});

describe('C-W2-05 automation Librarian',()=>{
  it('validates the redacted fixture contract and real WP-02 directory adapter',async()=>{ const fixture=JSON.parse(fs.readFileSync(path.resolve('automations/fixtures/librarian/repeated-failure-candidate.json'),'utf8')); expect(librarianAutomationRequestSchema.parse(fixture).domain).toBe('automation'); expect((await new Wp02PackageValidator(validateWp02Package).validate({proposal:{packagePath:'automations/packages/_golden-template',patch:{digest:patchDigest}}} as never)).passed).toBe(true); });
  it('resolves hashes, deduplicates, and verifies a release-bound WP-06 receipt',async()=>{ const items=values(), svc=service(items); const first=await svc.propose(makeRequest(items)); expect(first.candidate?.status).toBe('awaiting_review'); expect(await svc.propose(makeRequest(items))).toMatchObject({created:false,reason:'duplicate_evidence',candidate:{id:first.candidate?.id}}); });
  it('atomically reserves one candidate under concurrent duplicate delivery',async()=>{ const items=values(),store=new DurableMemoryLibrarianStore(),svc=service(items,store); const results=await Promise.all([svc.propose(makeRequest(items)),svc.propose(makeRequest(items))]); expect(results.filter((item)=>item.created)).toHaveLength(1); expect(new Set(results.map((item)=>item.candidate?.id)).size).toBe(1); });
  it('rejects forged, missing, cross-org, and duplicate-count evidence',async()=>{ const forged=values(); forged[0]={...forged[0],hash:sha256({forged:true})}; expect(await service(forged).propose(makeRequest(forged))).toMatchObject({reason:'evidence_hash_mismatch'}); const missing=values(); expect(await service([missing[0]]).propose(makeRequest(missing))).toMatchObject({reason:'evidence_not_found'}); const cross=values(); cross[1]={...cross[1],orgId:otherOrgId}; expect(await service(cross).propose(makeRequest(cross))).toMatchObject({reason:'cross_org_raw_evidence_rejected'}); const repeated=[evidence(),evidence({ref:'evidence://eval/duplicate',payload:validReceipt()})]; expect(await service(repeated).propose(makeRequest(repeated))).toMatchObject({reason:'trigger_policy_not_met'}); });
  it('authenticates de-identified aggregate approval issuer',async()=>{ const aggregate=evidence({ref:'evidence://aggregate/slo',orgId:undefined,payload:{measure:'p95'},aggregateApproval:{issuer:'institutional-aggregate-authority',approvalRef:'evidence://approval/slo',deidentified:true}}); expect((await service([aggregate]).propose(makeRequest([aggregate],{trigger:'scheduled_review'}))).created).toBe(true); const forged={...aggregate,aggregateApproval:{...aggregate.aggregateApproval!,issuer:'caller-self-approved'}}; expect(await service([forged]).propose(makeRequest([forged],{trigger:'scheduled_review'}))).toMatchObject({reason:'aggregate_approval_not_authenticated'}); });
  it('persists candidate, dedupe, global disable, and pause across service restart',async()=>{ const store=new DurableMemoryLibrarianStore(), items=values(); const first=service(items,store); const created=await first.propose(makeRequest(items)); const restarted=service(items,store); expect(await restarted.propose(makeRequest(items))).toMatchObject({reason:'duplicate_evidence',candidate:{id:created.candidate?.id}}); await restarted.setEnabled(orgId,false); expect(await service(items,store).propose(makeRequest(items))).toMatchObject({reason:'librarian_disabled_telemetry_retained'}); await restarted.setEnabled(orgId,true); await restarted.setAutomationPaused(orgId,'urgent-intake',true); expect(await service(items,store).propose(makeRequest(items))).toMatchObject({reason:'automation_paused_telemetry_retained'}); });
  it('derives proposer identity from auth and enforces independent org-scoped review',async()=>{ const items=values(), svc=service(items); expect(await svc.propose(makeRequest(items),'spoofed')).toMatchObject({reason:'actor_claim_mismatch'}); const candidate=(await svc.propose(makeRequest(items))).candidate!; await expect(svc.review(orgId,candidate.id,{decision:'approved',reason:'self'}, {id:candidate.proposerId,role:'independent_reviewer'})).rejects.toThrow('proposer cannot'); await expect(svc.review(otherOrgId,candidate.id,{decision:'approved',reason:'wrong org'}, {id:'reviewer:quality',role:'independent_reviewer'})).rejects.toThrow('not found'); await expect(svc.review(orgId,candidate.id,{decision:'approved',reason:'independent'}, {id:'reviewer:quality',role:'independent_reviewer'})).resolves.toMatchObject({status:'approved'}); });
  it('fails review readiness on WP-02 or an unbound WP-06 envelope',async()=>{ const items=values(); const failed:CandidateValidator={validate:async()=>({passed:false,evidenceRef:'evidence://wp02/fail'})}; expect((await service(items,new DurableMemoryLibrarianStore(),failed).propose(makeRequest(items))).candidate?.status).toBe('validation_failed'); const bad=values(),envelope=validReceipt(); envelope.receipt.packageDigest=sha256('wrong'); bad[0]=evidence({payload:envelope}); expect((await service(bad).propose(makeRequest(bad))).candidate?.status).toBe('eval_failed'); });
  it('rejects forged WP-06 HMAC signatures and ungoverned verifier references',async()=>{const forged=values(); const envelope=validReceipt(); envelope.verifier.signature='0'.repeat(64); forged[0]=evidence({payload:envelope}); expect((await service(forged).propose(makeRequest(forged))).candidate?.status).toBe('eval_failed'); const wrongRef=values(); wrongRef[0]={...wrongRef[0],verifierKeyRef:'gsm://attacker/key'}; expect((await service(wrongRef).propose(makeRequest(wrongRef))).candidate?.status).toBe('eval_failed');});
  it('rejects skill/brain domains and raw payload fields',()=>{ const items=values(); expect(()=>librarianAutomationRequestSchema.parse({...makeRequest(items),domain:'skills'})).toThrow(); expect(()=>librarianAutomationRequestSchema.parse({...makeRequest(items),rawClientPayload:{token:'secret'}})).toThrow(); });
  it('fails institutional authentication closed until a live JWKS verifier is configured',()=>{const now=Math.floor(Date.now()/1000),token=rsJwt(rsa.privateKey,'key-1',{iss:'https://librarian.example.test',aud:'linkautowork-librarian',sub:'reviewer:quality',org_id:orgId,role:'independent_reviewer',exp:now+60}); const request={header:(name:string)=>name==='x-librarian-institutional-token'?token:undefined} as never; const errors:unknown[]=[]; requireLibrarianInstitutionalClaim(productionEnv())(request,{} as never,(error?:unknown)=>{errors.push(error);}); expect(String(errors[0])).toContain('JWKS verifier is not configured'); });
  it('cryptographically proves distinct proposer/reviewer principals and rejects forged/expired claims',()=>{const secret='ltfx.ph.2f7c86b77a.v1',now=Math.floor(Date.now()/1000),base={iss:'https://librarian.test.linktrend.local',aud:'linkautowork-librarian',org_id:orgId,exp:now+60};const proposer=institutionalClaim(librarianJwt(secret,{...base,sub:'librarian:proposer',role:'proposer'}),institutionalEnv(secret));const reviewer=institutionalClaim(librarianJwt(secret,{...base,sub:'reviewer:quality',role:'independent_reviewer'}),institutionalEnv(secret));expect(proposer.error).toBeUndefined();expect(reviewer.error).toBeUndefined();expect(proposer.request.librarianInstitutional).not.toEqual(reviewer.request.librarianInstitutional);const token=librarianJwt(secret,{...base,sub:'attacker',role:'independent_reviewer'}),signatureStart=token.lastIndexOf('.')+1,forged=`${token.slice(0,signatureStart)}${token[signatureStart]==='a'?'b':'a'}${token.slice(signatureStart+1)}`;expect(institutionalClaim(forged,institutionalEnv(secret)).error).toBeTruthy();expect(institutionalClaim(librarianJwt(secret,{...base,sub:'expired',role:'independent_reviewer',exp:now-1}),institutionalEnv(secret)).error).toBeTruthy();});
  it('verifies production RS256/JWKS claims and rejects forged identity dimensions',async()=>{const provider=new FakeJwks(),now=Math.floor(Date.now()/1000),base={iss:'https://librarian.example.test',aud:'linkautowork-librarian',sub:'reviewer:quality',org_id:orgId,role:'independent_reviewer',exp:now+60};expect((await institutionalClaimAsync(rsJwt(rsa.privateKey,'key-1',base),productionEnv(),provider)).claim).toMatchObject({actorId:'reviewer:quality',orgId});expect((await institutionalClaimAsync(rsJwt(rotatedRsa.privateKey,'key-1',base),productionEnv(),provider)).error).toBeTruthy();expect((await institutionalClaimAsync(rsJwt(rsa.privateKey,'unknown',base),productionEnv(),provider)).error).toBeTruthy();expect((await institutionalClaimAsync(rsJwt(rsa.privateKey,'key-1',base,'HS256'),productionEnv(),provider)).error).toBeTruthy();for(const claims of [{...base,iss:'https://evil.test'},{...base,aud:'wrong'},{...base,org_id:otherOrgId},{...base,role:'publisher'},{...base,exp:now-1}])expect((await institutionalClaimAsync(rsJwt(rsa.privateKey,'key-1',claims),productionEnv(),provider)).error).toBeTruthy();});
  it('handles bounded JWKS rotation and fails closed when provider is unavailable',async()=>{const provider=new FakeJwks(),now=Math.floor(Date.now()/1000),claims={iss:'https://librarian.example.test',aud:'linkautowork-librarian',sub:'reviewer:rotated',org_id:orgId,role:'independent_reviewer',exp:now+60};provider.keys=new Map([['key-2',{...rotatedRsa.publicKey.export({format:'jwk'}),kid:'key-2',use:'sig'}]]);expect((await institutionalClaimAsync(rsJwt(rotatedRsa.privateKey,'key-2',claims),productionEnv(),provider)).claim).toBeTruthy();provider.unavailable=true;expect((await institutionalClaimAsync(rsJwt(rotatedRsa.privateKey,'key-2',claims),productionEnv(),provider)).error).toBeTruthy();});
  it('bounds remote JWKS caching and unknown-kid refresh attempts without a live call',async()=>{let calls=0;const jwk={...rsa.publicKey.export({format:'jwk'}),kid:'key-1',use:'sig'};const fetcher=async()=>{calls++;return new Response(JSON.stringify({keys:[jwk]}),{status:200,headers:{'content-type':'application/json'}});};const provider=new RemoteInstitutionalJwksProvider('https://local.invalid/jwks',300_000,fetcher);expect(await provider.get('key-1')).toMatchObject({kid:'key-1'});expect(await provider.get('key-1')).toBeTruthy();expect(await provider.get('unknown')).toBeUndefined();expect(await provider.get('another-unknown')).toBeUndefined();expect(calls).toBe(2);});
  it('uses the org-scoped gateway runtime JWT for Librarian RPCs',async()=>{const original=globalThis.fetch;const calls:Array<{headers?:HeadersInit}>=[];globalThis.fetch=async(_url,init)=>{calls.push({headers:init?.headers});return new Response('{}',{status:200,headers:{'content-type':'application/json'}});};try{const env={SUPABASE_URL:'https://db.test',SUPABASE_SERVICE_ROLE_KEY:'ltfx.automation.librarian.test.ts.apikey.44.2.v1',SUPABASE_RUNTIME_JWT:'scoped-runtime-jwt'} as AppEnv;await new SupabaseAuditClient(env).callLibrarianRpc('linkautowork_librarian_get_control',{p_org_id:orgId});expect(calls[0].headers).toMatchObject({apikey:'ltfx.ph.bb834239fd.v1',authorization:'Bearer scoped-runtime-jwt'});await expect(new SupabaseAuditClient({...env,SUPABASE_RUNTIME_JWT:undefined}).callLibrarianRpc('x',{p_org_id:orgId})).rejects.toThrow('runtime credential');}finally{globalThis.fetch=original;}});
});
