import { describe, expect, it } from 'vitest';
import { OperationsService, type ActionExecutor, type AlertAdapter, type DeploymentAuthority, type DeploymentExecutor, type HealthRecord, type MonitorTarget, type OperationsStore, type RetryOutboxItem } from '../src/services/monitoring/operations-service.js';
import { deploymentDecisionSchema, operationsActionSchema } from '../src/contracts/operations.js';

const orgA = '00000000-0000-0000-0000-000000000001'; const orgB = '00000000-0000-0000-0000-000000000002'; const instanceId = '40000000-0000-0000-0000-000000000001';
class FakeStore implements OperationsStore {
  targets: MonitorTarget[] = []; health: HealthRecord[] = []; alerts = new Map<string, { alertId: string; incidentId: string; open: boolean }>(); actions: Record<string, unknown>[] = []; deployments: Record<string, unknown>[] = []; pauses: Record<string, unknown>[] = [];
  async listMonitorTargets(orgId: string) { return this.targets.filter((target) => target.orgId === orgId); }
  async writeHealth(record: HealthRecord) { this.health.push(record); }
  async openAlertIncident(args: { orgId: string; instanceId: string; routingKey: string }) { const key = `${args.orgId}:${args.instanceId}:${args.routingKey}`; const prior = this.alerts.get(key); if (prior?.open) return { ...prior, deliver: false }; const value = { alertId: `10000000-0000-0000-0000-${String(this.alerts.size + 1).padStart(12, '0')}`, incidentId: `20000000-0000-0000-0000-${String(this.alerts.size + 1).padStart(12, '0')}`, open: true }; this.alerts.set(key, value); return { ...value, deliver: true }; }
  async recoverAlertIncident(args: { orgId: string; instanceId: string; routingKey: string }) { const key = `${args.orgId}:${args.instanceId}:${args.routingKey}`; const value = this.alerts.get(key); if (!value?.open) return undefined; value.open = false; return { alertId: value.alertId, deliver: true }; }
  async listHealth(orgId: string) { return this.health.filter((record) => record.orgId === orgId); }
  async transitionIncident() {} async recordAction(args: Record<string, unknown>) { this.actions.push(args); } async recordDeployment(args: Record<string, unknown>) { this.deployments.push(args); } async writePause(args: Record<string, unknown>) { this.pauses.push(args); } async runMaintenance(orgId: string) { return [{ instanceId, findings: [`org:${orgId}`] }]; }
  async authorizeAction() { return { allowed: true, supportsFailover: false, currentWorkflowId: 'current', baselineWorkflowId: 'baseline' }; }
  async loadDeploymentAuthority(): Promise<DeploymentAuthority> { return { baselineDeploymentId: '50000000-0000-0000-0000-000000000002', candidateReleaseId: '60000000-0000-0000-0000-000000000001', baselineReleaseId: '60000000-0000-0000-0000-000000000002', candidateWorkflowId: 'candidate', baselineWorkflowId: 'baseline', compatibleBindings: true, candidateCertified: true, baselineCertified: true, approvalRef: 'evidence://approval/1', healthEvidenceRef: 'evidence://canary/1', sampleCount: 5, minimumSamples: 5, elapsedMs: 10_000, minimumWindowMs: 10_000, candidateSuccessRate: .5, baselineSuccessRate: .9 }; }
  retry?: RetryOutboxItem; retryResults: Array<{ delivered: boolean; error?: string }> = []; async claimRetry() { const value = this.retry; this.retry = undefined; return value; } async completeRetry(_orgId: string, _id: string, delivered: boolean, error?: string) { this.retryResults.push({ delivered, error }); }
  transitionDisposition: 'prepared' | 'replay' | 'in_progress' = 'prepared'; commitFails = false; transitionFailures: Array<{ error: string; compensationFailed: boolean }> = [];
  async prepareDeployment() { return { transitionId: '80000000-0000-0000-0000-000000000001', disposition: this.transitionDisposition, authority: await this.loadDeploymentAuthority(), committedRecord: this.transitionDisposition === 'replay' ? { replayed: true } : undefined }; }
  async commitDeployment(_orgId: string, _transitionId: string, record: Record<string, unknown>) { if (this.commitFails) throw new Error('commit conflict'); this.deployments.push(record); }
  async failDeployment(_orgId: string, _transitionId: string, error: string, compensationFailed: boolean) { this.transitionFailures.push({ error, compensationFailed }); }
}
const executors = (fail = false): ActionExecutor => ({ retry: async () => { if (fail) throw new Error('queue unavailable'); return { queued: true }; }, pause: async () => ({ state: 'paused' }), failover: async () => ({ switched: true }), rollback: async () => ({ state: 'rolled_back' }) });
const deployments: DeploymentExecutor = { apply: async () => undefined, compensate: async () => undefined };
const retryDispatcher = { dispatch: async () => undefined };
const target = (orgId = orgA): MonitorTarget => ({ orgId, automationId: 'daily-ops', instanceId, cadenceMs: 60_000, graceMs: 10_000, lastExpectedAt: '2026-08-04T00:00:00.000Z', enabled: true, executions: [{ executionId: 'e1', status: 'accepted', acceptedAt: '2026-08-04T00:00:00.000Z', retryCount: 0 }] });

describe('durable WP-08 gateway operations', () => {
  it('rejects caller-supplied authority booleans and canary metrics', () => { expect(() => operationsActionSchema.parse({ kind: 'retry', instanceId, reason: 'forged authority', evidenceRef: 'evidence://forged/1', allowlisted: true })).toThrow(); expect(() => deploymentDecisionSchema.parse({ deploymentId: '50000000-0000-0000-0000-000000000001', action: 'promote', reason: 'forged metrics', candidateCertified: true, candidateSuccessRate: 1 })).toThrow(); });
  it('detects accepted/started no-callback and deduplicates across service restart', async () => { const store = new FakeStore(); store.targets = [target()]; const delivered: string[] = []; const adapter: AlertAdapter = { deliver: async (a) => { delivered.push(a.alertId); } }; await new OperationsService(store, adapter, executors(), deployments, retryDispatcher, () => new Date('2026-08-04T00:02:00Z')).monitor(orgA); await new OperationsService(store, adapter, executors(), deployments, retryDispatcher, () => new Date('2026-08-04T00:02:01Z')).monitor(orgA); expect(store.health.at(-1)).toMatchObject({ staleCallback: true, missingSchedule: true }); expect(delivered).toHaveLength(1); });
  it('never returns or processes another organisation target', async () => { const store = new FakeStore(); store.targets = [target(orgA), target(orgB)]; const service = new OperationsService(store, { deliver: async () => undefined }, executors(), deployments, retryDispatcher, () => new Date('2026-08-04T00:02:00Z')); await service.monitor(orgA); expect(await service.health(orgA)).toHaveLength(1); expect((await service.health(orgA))[0]?.orgId).toBe(orgA); });
  it('audits an invoked executor failure instead of reporting success', async () => { const store = new FakeStore(); const result = await new OperationsService(store, { deliver: async () => undefined }, executors(true), deployments, retryDispatcher).executeAction({ orgId: orgA, actor: 'operator', kind: 'retry', instanceId, reason: 'bounded retry', evidenceRef: 'evidence://incident/1' }); expect(result).toMatchObject({ result: 'failed', error: 'queue unavailable' }); expect(store.actions[0]).toMatchObject({ result: 'failed', error: 'queue unavailable' }); });
  it('ignores forged caller metrics and uses durable canary authority', async () => { const store = new FakeStore(); const service = new OperationsService(store, { deliver: async () => undefined }, executors(), deployments, retryDispatcher); const request = { orgId: orgA, actor: 'approver', deploymentId: '50000000-0000-0000-0000-000000000001', reason: 'durable regression', idempotencyKey: 'deploy-request-1' }; await expect(service.deployment({ ...request, action: 'promote' })).rejects.toThrow(/insufficient/); const rollback = await service.deployment({ ...request, action: 'rollback' }); expect(rollback?.evidenceDigest).toMatch(/^sha256:/); expect(store.deployments).toHaveLength(1); });
  it('binds pause records to the claimed organisation', async () => { const store = new FakeStore(); const service = new OperationsService(store, { deliver: async () => undefined }, executors(), deployments, retryDispatcher); await service.pause({ orgId: orgA, scope: 'organisation', active: true, actor: 'operator', reason: 'incident containment', evidenceRef: 'evidence://incident/2' }); expect(store.pauses[0]).toMatchObject({ orgId: orgA, scope: 'organisation' }); });
  it('delivers recovery through the adapter after durable resolution', async () => { const store = new FakeStore(); store.targets = [target()]; const delivered: boolean[] = []; const service = new OperationsService(store, { deliver: async (alert) => { delivered.push(alert.recovered); } }, executors(), deployments, retryDispatcher, () => new Date('2026-08-04T00:02:00Z')); await service.monitor(orgA); store.targets = [{ ...target(), lastExpectedAt: '2026-08-04T00:01:30Z', executions: [{ executionId: 'e2', status: 'succeeded', acceptedAt: '2026-08-04T00:01:30Z', startedAt: '2026-08-04T00:01:31Z', completedAt: '2026-08-04T00:01:32Z', callbackAt: '2026-08-04T00:01:33Z', retryCount: 0 }] }]; await service.monitor(orgA); expect(delivered).toEqual([false, true]); });
  it('persists failed outbox delivery for retry after restart', async () => { const store = new FakeStore(); store.retry = { id: '90000000-0000-0000-0000-000000000001', orgId: orgA, instanceId, webhookPath: '/retry', method: 'POST' }; const service = new OperationsService(store, { deliver: async () => undefined }, executors(), deployments, { dispatch: async () => { throw new Error('n8n unavailable'); } }); expect(await service.deliverRetry(orgA)).toMatchObject({ delivered: false, error: 'n8n unavailable' }); expect(store.retryResults).toEqual([{ delivered: false, error: 'n8n unavailable' }]); });
  it('compensates n8n when authoritative commit fails and supports replay', async () => { const store = new FakeStore(); store.commitFails = true; const calls: string[] = []; const executor: DeploymentExecutor = { apply: async () => { calls.push('apply'); }, compensate: async () => { calls.push('compensate'); } }; const service = new OperationsService(store, { deliver: async () => undefined }, executors(), executor, retryDispatcher); await expect(service.deployment({ orgId: orgA, actor: 'operator', deploymentId: '50000000-0000-0000-0000-000000000001', action: 'rollback', reason: 'regression', idempotencyKey: 'rollback-request-1' })).rejects.toThrow('commit conflict'); expect(calls).toEqual(['apply', 'compensate']); expect(store.transitionFailures[0]).toMatchObject({ compensationFailed: false }); store.transitionDisposition = 'replay'; expect(await service.deployment({ orgId: orgA, actor: 'operator', deploymentId: '50000000-0000-0000-0000-000000000001', action: 'rollback', reason: 'regression', idempotencyKey: 'rollback-request-1' })).toEqual({ replayed: true }); });
  it('marks an unresolved compensation failure without committing resolver state', async () => { const store = new FakeStore(); store.commitFails = true; const executor: DeploymentExecutor = { apply: async () => undefined, compensate: async () => { throw new Error('compensation unavailable'); } }; const service = new OperationsService(store, { deliver: async () => undefined }, executors(), executor, retryDispatcher); await expect(service.deployment({ orgId: orgA, actor: 'operator', deploymentId: '50000000-0000-0000-0000-000000000001', action: 'rollback', reason: 'regression', idempotencyKey: 'rollback-request-2' })).rejects.toThrow('commit conflict'); expect(store.deployments).toHaveLength(0); expect(store.transitionFailures[0]?.compensationFailed).toBe(true); });
});
