import { describe, expect, it } from 'vitest';
import { OperationsLedger, ProbeRunner, assessCanary, checkMaintenance, deriveHealth, effectivePause, healthView, rehearseRestore, remediate, type AlertAdapter, type BackupArtifact } from '../src/index.js';
import { createHash } from 'node:crypto';

const orgId = '00000000-0000-0000-0000-000000000001'; const instanceId = '60000000-0000-0000-0000-000000000001'; const automationId = 'ops-ritual';
const digest = (value: unknown) => `sha256:${createHash('sha256').update(JSON.stringify(value)).digest('hex')}`;
describe('WP-08 operations safety contracts', () => {
  it('detects a missing scheduled job and opens one deduplicated alert and incident', async () => { const sent: string[] = []; const ledger = new OperationsLedger({ deliver: async (alert) => { sent.push(alert.id); } } satisfies AlertAdapter); const health = deriveHealth({ orgId, automationId, instanceId, cadenceMs: 60_000, graceMs: 10_000, lastExpectedAt: '2026-08-04T00:00:00.000Z', enabled: true }, [], Date.parse('2026-08-04T00:02:00.000Z')); expect(health).toMatchObject({ health: 'unhealthy', missingSchedule: true }); const first = await ledger.alert({ orgId, instanceId, severity: 'critical', routingKey: 'missing-run', reason: 'scheduled run absent', repeatIntervalMs: 60_000, at: '2026-08-04T00:02:00.000Z' }); const second = await ledger.alert({ orgId, instanceId, severity: 'critical', routingKey: 'missing-run', reason: 'scheduled run absent', repeatIntervalMs: 60_000, at: '2026-08-04T00:02:30.000Z' }); expect(second.id).toBe(first.id); expect(sent).toHaveLength(1); expect(ledger.incidents.get(first.incidentId)?.status).toBe('open'); });
  it('supports ordered incident history, recovery, and local adapter failure isolation', async () => { const ledger = new OperationsLedger({ deliver: async () => undefined }); const alert = await ledger.alert({ orgId, instanceId, severity: 'warning', routingKey: 'slow', reason: 'slow', repeatIntervalMs: 1 }); ledger.transition(alert.incidentId, 'acknowledged', 'operator', 'ack'); ledger.transition(alert.incidentId, 'investigating', 'operator', 'inspect', ['evidence://ops/one']); ledger.recover(alert.id); expect(ledger.incidents.get(alert.incidentId)?.history.map((entry) => entry.action)).toEqual(['opened', 'ack', 'inspect', 'recovery_notified']); expect(() => ledger.transition(alert.incidentId, 'open', 'operator', 'undo')).toThrow(); });
  it('classifies failure, detects stale callbacks, rate-limits safe probes, and rejects forbidden remediation', async () => { const health = deriveHealth({ orgId, automationId, instanceId, cadenceMs: 1_000, graceMs: 100, lastExpectedAt: '2026-08-04T00:00:00.000Z', enabled: true }, [{ orgId, automationId, instanceId, executionId: 'e1', status: 'failed', occurredAt: '2026-08-04T00:00:00.000Z', retryCount: 1, failureHint: 'credential invalid' }], Date.parse('2026-08-04T00:00:01.000Z')); expect(health).toMatchObject({ staleCallback: true, failures: ['credential'] }); const runner = new ProbeRunner(); const probe = { name: 'safe-status', safe: true as const, minIntervalMs: 1000, run: async () => ({ ok: true }) }; expect((await runner.run(probe, 1)).skipped).toBe(false); expect((await runner.run(probe, 2)).skipped).toBe(true); expect(remediate('rollback_certified', ['retry'], { actor: 'monitor', reason: 'test', evidenceRefs: [], before: {}, after: {} }).result).toBe('rejected'); });
  it('reports bounded maintenance findings and keeps organisation views scoped', () => { const findings = checkMaintenance({ versionDrift: true, disabledWorkflow: false, staleCallback: false, credentialState: 'expiring', dependenciesTested: false, storagePressure: false, queuePressure: true, backupFresh: false, unresolvedIncidentCount: 1 }); expect(findings.map((finding) => finding.code)).toContain('backup_stale'); const one = deriveHealth({ orgId, automationId, instanceId, cadenceMs: 1, graceMs: 1, lastExpectedAt: '2026-08-04T00:00:00Z', enabled: false }, []); const other = { ...one, orgId: '00000000-0000-0000-0000-000000000002' }; expect(healthView([one, other], orgId)).toEqual([one]); });
  it('holds insufficient canaries, rolls back regressions, records precedence, and restores disposable artifacts', () => { const canary = { id: 'c', orgId, instanceIds: [instanceId], candidateReleaseId: 'candidate', baselineReleaseId: 'baseline', minimumSamples: 5, minimumWindowMs: 1000, startedAt: '2026-08-04T00:00:00Z', candidateSuccessRate: .5, baselineSuccessRate: .9, status: 'canary' as const }; expect(assessCanary(canary, { samples: 1, elapsedMs: 2000, compatibleBindings: true, baselineCertified: true, authorised: true })).toBe('hold'); expect(assessCanary(canary, { samples: 5, elapsedMs: 2000, compatibleBindings: true, baselineCertified: true, authorised: true })).toBe('rollback'); expect(effectivePause([{ scope: 'instance', instanceId, reason: 'local' }, { scope: 'global', reason: 'emergency' }], { orgId, automationId, instanceId })?.reason).toBe('emergency'); const kinds: BackupArtifact['kind'][] = ['control_records', 'catalogue_receipts', 'workflow_configuration']; const artifacts: BackupArtifact[] = kinds.map((kind) => { const content = { kind, reference: `${kind}-only` }; return { kind, content, digest: digest(content) }; }); expect(rehearseRestore(artifacts).artifacts).toHaveLength(3); });
});
