import assert from 'node:assert/strict';
import { createHmac } from 'node:crypto';
import { existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { createServer, type Server } from 'node:http';
import { basename, extname, resolve } from 'node:path';
import { chromium, type Browser, type Page } from 'playwright';
import { createProductApi } from '../../product-api/src/app.js';
import { createPostgrestRpc } from '../../product-api/src/postgrest.js';
import { InMemoryProductApiService, PostgrestProductApiService, PostgrestProvisioningAdapter } from '../../product-api/src/service.js';

const issuer = 'https://platform.browser.test'; const audience = 'linkautowork-product-api'; const secret = 'ltfx.ph.3d3b53a922.v1';
const org = '00000000-0000-0000-0000-000000000002';
const stepTimeoutMs = 8_000;
/* Chrome can take several seconds to settle its child processes after a real browser run; this remains bounded. */
const shutdownTimeoutMs = 15_000;
async function step<T>(name: string, work: () => Promise<T>, timeoutMs = stepTimeoutMs): Promise<T> {
  console.log(`Browser E2E step: ${name}`);
  let timer: ReturnType<typeof setTimeout> | undefined;
  try {
    return await Promise.race([work(), new Promise<T>((_resolve, reject) => { timer = setTimeout(() => reject(new Error(`Browser E2E timed out during ${name} after ${timeoutMs}ms`)), timeoutMs); })]);
  } finally { if (timer) clearTimeout(timer); }
}
async function settle(name: string, work: () => Promise<void>) { try { await step(name, work, shutdownTimeoutMs); } catch (error) { console.error(`Browser E2E cleanup warning (${name}):`, error instanceof Error ? error.message : error); } }
function token(roles: string[]) { const header = Buffer.from(JSON.stringify({ alg: 'HS256', typ: 'JWT' })).toString('base64url'); const payload = Buffer.from(JSON.stringify({ iss: issuer, aud: audience, sub: `browser-${roles[0]}`, org_id: org, roles, exp: Math.floor(Date.now() / 1000) + 300 })).toString('base64url'); return `${header}.${payload}.${createHmac('sha256', secret).update(`${header}.${payload}`).digest('base64url')}`; }
async function listen(server: Server) { await new Promise<void>((resolveListen) => server.listen(0, '127.0.0.1', resolveListen)); const address = server.address(); assert(address && typeof address !== 'string'); return `http://127.0.0.1:${address.port}`; }
async function staticServer(dist: string, config: Record<string, unknown>) { const publicRoot = resolve(dist, 'public'); const sourceRoot = resolve(dist, 'src'); return createServer(async (request, response) => { const path = request.url?.split('?')[0] ?? '/'; if (path === '/runtime-config.json') { response.writeHead(200, { 'content-type': 'application/json', 'cache-control': 'no-store' }); response.end(JSON.stringify(config)); return; } const target = path === '/' ? resolve(publicRoot, 'index.html') : path.startsWith('/src/') ? resolve(sourceRoot, basename(path)) : resolve(publicRoot, basename(path)); if (![publicRoot, sourceRoot].some((root) => target.startsWith(`${root}/`))) { response.writeHead(404).end(); return; } try { const content = await readFile(target); response.writeHead(200, { 'content-type': ({ '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json' }[extname(target)] ?? 'application/octet-stream') }); response.end(content); } catch { response.writeHead(404).end(); } }); }
async function pageWithSession(browser: Browser, name: string, url: string, accessToken: string, roles: string[], mobile = false) {
  const context = await step(`${name}: create browser context`, () => browser.newContext(mobile ? { viewport: { width: 390, height: 844 } } : {}));
  await step(`${name}: inject test-only governed session`, () => context.addInitScript(({ accessToken: supplied, roles: suppliedRoles }) => { window.LINKAUTOWORK_CLIENT_SESSION = { accessToken: supplied, subject: 'browser-client', organisationId: '00000000-0000-0000-0000-000000000002', roles: suppliedRoles as ['client_admin'] }; window.LINKAUTOWORK_OPERATOR_SESSION = { accessToken: supplied, subject: 'browser-operator', roles: suppliedRoles as ['operator'] }; }, { accessToken, roles }));
  const page = await step(`${name}: create page`, () => context.newPage());
  page.on('console', (message) => console.error(`browser console ${name}: ${message.type()} ${message.text()}`));
  page.on('pageerror', (error) => console.error(`browser page error ${name}: ${error.message}`));
  page.on('requestfailed', (request) => console.error(`browser request failed ${name}: ${request.url()} ${request.failure()?.errorText}`));
  page.on('response', (response) => { if (response.url().includes('/v1/')) { const prefix = `browser API response ${name}: ${response.status()} ${response.url()}`; if (response.status() < 400) console.error(prefix); else void response.text().then((body) => console.error(`${prefix} ${body}`)).catch(() => undefined); } });
  page.setDefaultTimeout(stepTimeoutMs);
  await step(`${name}: load page`, () => page.goto(url, { waitUntil: 'domcontentloaded', timeout: stepTimeoutMs }));
  return { page, context };
}
let productBase = '';
async function expectAccessibleShell(page: Page) { await page.waitForSelector('h1'); assert.equal(await page.locator('h1').count(), 1, 'page must have one primary heading'); assert.equal(await page.locator('button').allTextContents().then((items) => items.every((item) => item.trim().length > 0)), true, 'all buttons need accessible text'); }

const service = process.env.DURABLE_POSTGREST_URL && process.env.DURABLE_POSTGREST_JWT_SECRET
  ? (() => { const header = Buffer.from(JSON.stringify({ alg: 'HS256', typ: 'JWT' })).toString('base64url'); const payload = Buffer.from(JSON.stringify({ role: 'service_role', exp: Math.floor(Date.now() / 1000) + 300 })).toString('base64url'); const bearer = `${header}.${payload}.${createHmac('sha256', process.env.DURABLE_POSTGREST_JWT_SECRET!).update(`${header}.${payload}`).digest('base64url')}`; const rpc = createPostgrestRpc({ restUrl: process.env.DURABLE_POSTGREST_URL!, rpcPath: '', serviceRoleToken: bearer }); return new PostgrestProductApiService(rpc, new PostgrestProvisioningAdapter(rpc)); })()
  : new InMemoryProductApiService([{ id: 'briefing', name: 'Browser proof automation', summary: 'A managed browser-proof automation.', version: 1, signupPrerequisites: ['operator-assisted configuration'] }], [{ id: 'instance-a', orgId: org, state: 'active', configurationStatus: 'operator_assisted_required', deploymentStatus: 'active', health: 'healthy', executions: [], incidents: [], approvedOutputs: [], supportRequests: [] }], { incidents: [{ id: 'incident-redacted', summary: 'authorization token must never render', state: 'open', version: 1 }], releases: [{ id: 'release-certified', summary: 'Immutable certified release', status: 'certified', version: 1, evidenceRef: 'evidence://operator/release' }], deployments: [{ id: 'deployment-1', summary: 'Certified release deployment', state: 'ready', version: 1 }] });
let productApp: ReturnType<typeof createProductApi> | undefined;
const product = createServer((request, response) => { if (!productApp) { response.writeHead(503).end(); return; } productApp(request, response); });
let browser: Browser | undefined;
let web: Server | undefined;
let operator: Server | undefined;
try {
  const webConfig: Record<string, unknown> = { productApiOrigin: '', testMode: true }; const operatorConfig: Record<string, unknown> = { productApiOrigin: '', testMode: true }; web = await staticServer(resolve(import.meta.dirname, '../dist'), webConfig); operator = await staticServer(resolve(import.meta.dirname, '../../operator-console/dist'), operatorConfig); const webBase = await listen(web); const operatorBase = await listen(operator); productApp = createProductApi({ nodeEnv: 'test', issuer, audience, testJwtSecret: secret, webhookSecret: 'ltfx.ph.ec0f854dfd.v1', publicClientOrigin: webBase, operatorConsoleOrigin: operatorBase }, service); productBase = await listen(product); webConfig.productApiOrigin = productBase; operatorConfig.productApiOrigin = productBase; if (process.env.DURABLE_POSTGREST_URL) console.log('Durable RPC preflight:', await service.publishedProducts({ limit: 25 })); console.log('Product preflight:', await fetch(`${productBase}/v1/public/products`).then(async (response) => `${response.status} ${await response.text()}`)); console.log('Separate-host topology preflight:', await fetch(`${productBase}/v1/public/products`).then((response) => `${response.status} ${new URL(productBase).origin}`));
  const requestedBrowser = process.env.PLAYWRIGHT_CHROME_EXECUTABLE_PATH;
  const localMacChrome = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
  const executablePath = requestedBrowser || (existsSync(localMacChrome) ? localMacChrome : undefined);
  browser = await step('launch Chrome', () => chromium.launch({ headless: true, ...(executablePath ? { executablePath } : {}) }), 20_000);
  console.log('Browser E2E: client portal'); const client = await pageWithSession(browser, 'client portal', webBase, token(['client_admin']), ['client_admin'], true); await step('client portal: accessibility shell', () => expectAccessibleShell(client.page)); await step('client portal: request button visible', () => client.page.getByRole('button', { name: 'Request this automation' }).waitFor()); await step('client portal: lifecycle handlers ready', () => client.page.getByText(/No active instance yet|Provisioning requests:/i).waitFor()); await step('client portal: request lifecycle', () => client.page.getByRole('button', { name: 'Request this automation' }).dblclick()); await step('client portal: request receipt', () => client.page.getByText(/request was recorded/i).waitFor()); assert.match(await client.page.locator('#status').textContent() ?? '', /request was recorded/i); assert.equal(await client.page.locator('input[type="password"], input[name*="token" i], input[name*="credential" i]').count(), 0); assert.equal(await client.page.locator('header').evaluate((node) => getComputedStyle(node).display), 'block'); assert.equal(client.page.viewportSize()?.width, 390, 'client portal must prove responsive mobile viewport'); await step('client portal: refresh retains request intent', () => client.page.reload({ waitUntil: 'domcontentloaded' })); assert.equal(await client.page.getByText(/request was recorded/i).count(), 0); await step('client portal: close context', () => client.context.close());
  console.log('Browser E2E: operator denial'); const denied = await pageWithSession(browser, 'operator denial', `${operatorBase}#incidents`, token(['client_member']), ['client_member']); await step('operator denial: rejected shell visible', () => denied.page.getByText('not authorised').waitFor()); await step('operator denial: accessibility shell', () => expectAccessibleShell(denied.page)); assert.equal(await denied.page.getByRole('button').count(), 0, 'client members must not receive operator action controls'); await step('operator denial: close context', () => denied.context.close());
  console.log('Browser E2E: operator recovery'); const operatorPage = await pageWithSession(browser, 'operator recovery', `${operatorBase}#incidents`, token(['operator']), ['operator']); await step('operator recovery: incident heading', () => operatorPage.page.getByRole('heading', { name: 'Incident centre', exact: true }).waitFor()); assert.match(await operatorPage.page.locator('main').textContent() ?? '', /Incident/); await step('operator recovery: acknowledge scope', () => operatorPage.page.getByRole('button', { name: /Review acknowledge scope/i }).click()); await operatorPage.page.getByRole('textbox', { name: 'Reason' }).fill('Acknowledged after browser proof'); await operatorPage.page.getByRole('checkbox').check(); await operatorPage.page.getByRole('button', { name: /Confirm acknowledge/i }).click(); await step('operator recovery: acknowledgement receipt', () => operatorPage.page.getByRole('status').waitFor()); assert.match(await operatorPage.page.getByRole('status').textContent() ?? '', /Audit receipt/i); await step('operator recovery: resolve scope', () => operatorPage.page.getByRole('button', { name: /Review resolve scope/i }).click()); await operatorPage.page.getByRole('textbox', { name: 'Reason' }).fill('Resolved after durable recovery evidence'); await operatorPage.page.getByRole('checkbox').check(); await operatorPage.page.getByRole('button', { name: /Confirm resolve/i }).click(); await operatorPage.page.getByRole('status').waitFor();
  const provisioning = await pageWithSession(browser, 'provisioning retry', `${operatorBase}#provisioning`, token(['operator']), ['operator']); await provisioning.page.getByRole('button', { name: /Review retry scope/i }).click(); await provisioning.page.getByRole('textbox', { name: 'Reason' }).fill('Retry failed provisioning after operator review'); await provisioning.page.getByRole('checkbox').check(); await provisioning.page.getByRole('button', { name: /Confirm retry/i }).click(); await provisioning.page.getByRole('status').waitFor(); await provisioning.context.close();
  const instance = await pageWithSession(browser, 'instance pause resume', `${operatorBase}#instances`, token(['operator']), ['operator']); await instance.page.getByRole('button', { name: /Review pause scope/i }).click(); await instance.page.getByRole('textbox', { name: 'Reason' }).fill('Pause for maintenance window'); await instance.page.getByRole('checkbox').check(); await instance.page.getByRole('button', { name: /Confirm pause/i }).click(); await instance.page.getByRole('status').waitFor(); await instance.page.getByRole('button', { name: /Review resume scope/i }).click(); await instance.page.getByRole('textbox', { name: 'Reason' }).fill('Resume after maintenance window'); await instance.page.getByRole('checkbox').check(); await instance.page.getByRole('button', { name: /Confirm resume/i }).click(); await instance.page.getByRole('status').waitFor(); await instance.context.close();
  const certification = await pageWithSession(browser, 'certification separation', `${operatorBase}#certification`, token(['operator']), ['operator']); await certification.page.getByRole('button', { name: /Review approve scope/i }).waitFor(); assert.equal(await certification.page.getByRole('button', { name: /Review approve scope/i }).isDisabled(), true); await certification.context.close(); const approverCertification = await pageWithSession(browser, 'certification approval', `${operatorBase}#certification`, token(['approver']), ['approver']); await approverCertification.page.getByRole('button', { name: /Review approve scope/i }).click(); await approverCertification.page.getByRole('textbox', { name: 'Reason' }).fill('Independent evaluation receipt reviewed'); await approverCertification.page.getByRole('checkbox').check(); await approverCertification.page.getByRole('button', { name: /Confirm approve/i }).click(); await approverCertification.page.getByRole('status').waitFor(); await approverCertification.context.close();
  const releases = await pageWithSession(browser, 'certified releases read-only', `${operatorBase}#releases`, token(['operator']), ['operator']); const releaseRead = await Promise.all([releases.page.waitForResponse((response) => response.url().includes('/v1/operator/releases?limit=25')), releases.page.reload({ waitUntil: 'domcontentloaded' })]).then(([response]) => response); assert.equal(releaseRead.status(), 200); await releases.page.getByRole('heading', { name: 'Certified releases', exact: true }).waitFor(); assert.match(await releases.page.locator('main').textContent() ?? '', /Immutable certified release/); assert.equal(await releases.page.getByRole('button').count(), 0, 'certified releases must not expose deployment actions'); await releases.context.close();
  const canary = await pageWithSession(browser, 'canary operator', `${operatorBase}#deployments`, token(['operator']), ['operator']); const deploymentRead = await Promise.all([canary.page.waitForResponse((response) => response.url().includes('/v1/operator/deployments?limit=25')), canary.page.reload({ waitUntil: 'domcontentloaded' })]).then(([response]) => response); assert.equal(deploymentRead.status(), 200); await canary.page.getByRole('heading', { name: 'Deployments', exact: true }).waitFor(); await canary.page.locator('[data-record-id="50000000-0000-0000-0000-000000000011"][data-action="canary"]').click(); await canary.page.getByRole('textbox', { name: 'Reason' }).fill('Start bounded canary with approved evidence'); await canary.page.getByRole('checkbox').check(); await canary.page.getByRole('button', { name: /Confirm canary/i }).click(); await canary.page.getByRole('status').waitFor(); const operatorPromotion = canary.page.locator('[data-record-id="50000000-0000-0000-0000-000000000011"][data-action="promote"]'); await operatorPromotion.waitFor(); assert.equal(await operatorPromotion.isDisabled(), true); await canary.context.close();
  const promotion = await pageWithSession(browser, 'promotion approval', `${operatorBase}#deployments`, token(['approver']), ['approver']); await promotion.page.locator('[data-record-id="50000000-0000-0000-0000-000000000011"][data-action="promote"]').click(); await promotion.page.getByRole('textbox', { name: 'Reason' }).fill('Promote only after canary sample and health evidence'); await promotion.page.getByRole('checkbox').check(); await promotion.page.getByRole('button', { name: /Confirm promote/i }).click(); await promotion.page.getByRole('status').waitFor(); await promotion.page.locator('[data-record-id="50000000-0000-0000-0000-000000000011"][data-action="rollback"]').click(); await promotion.page.getByRole('textbox', { name: 'Reason' }).fill('Rollback to certified baseline after operator review'); await promotion.page.getByRole('checkbox').check(); await promotion.page.getByRole('button', { name: /Confirm rollback/i }).click(); await promotion.page.getByRole('status').waitFor(); await promotion.context.close();
  const maintenance = await pageWithSession(browser, 'maintenance action', `${operatorBase}#maintenance`, token(['operator']), ['operator']); await maintenance.page.getByRole('button', { name: /Review retry scope/i }).click(); await maintenance.page.getByRole('textbox', { name: 'Reason' }).fill('Run approved bounded retry maintenance'); await maintenance.page.getByRole('checkbox').check(); await maintenance.page.getByRole('button', { name: /Confirm retry/i }).click(); await maintenance.page.getByRole('status').waitFor(); await maintenance.context.close();
  const librarian = await pageWithSession(browser, 'librarian approval', `${operatorBase}#librarian`, token(['approver']), ['approver']); await librarian.page.getByRole('button', { name: /Review approve scope/i }).click(); await librarian.page.getByRole('textbox', { name: 'Reason' }).fill('Review candidate evidence and evaluation results'); await librarian.page.getByRole('checkbox').check(); await librarian.page.getByRole('button', { name: /Confirm approve/i }).click(); await librarian.page.getByRole('status').waitFor(); await librarian.context.close();
  const audit = await pageWithSession(browser, 'audit evidence', `${operatorBase}#audit-health`, token(['operator']), ['operator']); await audit.page.getByRole('heading', { name: 'Audit and system health', exact: true }).waitFor(); assert.match(await audit.page.locator('main').textContent() ?? '', /evidence:\/\//i); await audit.context.close();
  console.log('Playwright browser E2E passed: durable operator reads, provisioning retry, instance pause/resume, incident recovery, certification approval separation, canary/promotion/rollback, maintenance, Librarian review, audit evidence, redaction, and client lifecycle.');
} finally { await settle('close browser', async () => { await browser?.close(); }); const servers = [product, web, operator].filter((server): server is Server => Boolean(server)); for (const server of servers) server.closeAllConnections(); await Promise.all(servers.map((server, index) => settle(`close server ${index + 1}`, () => new Promise<void>((resolveClose) => server.close(() => resolveClose()))))); }
