import { describe, expect, it } from 'vitest';
import { readFile } from 'node:fs/promises';
import { actionAvailability, allowed, routeFor } from '../src/console.js';
import { isOperatorActionAllowed, ProductApiClient, operatorResources } from '../src/api.js';
describe('WP-10 authenticated operator shell', () => {
  it('denies client roles and keeps certification/promotion separated from routine operator work', () => { expect(allowed({ subject: 'client', roles: ['client_member'] })).toBe(false); expect(actionAvailability({ subject: 'operator', roles: ['operator'] }, 'promote')).toMatchObject({ allowed: false }); expect(actionAvailability({ subject: 'operator', roles: ['operator'] }, 'approve')).toMatchObject({ allowed: false }); expect(actionAvailability({ subject: 'approver', roles: ['approver'] }, 'promote')).toMatchObject({ allowed: true }); expect(routeFor('#certification')).toBe('certification'); expect(routeFor('#deployments')).toBe('deployments'); expect(routeFor('#unknown')).toBe('overview'); });
  it('uses distinct finite release and deployment routes and keeps actions resource-bounded', async () => { const calls: string[] = []; const client = new ProductApiClient({ get: async (path) => { calls.push(path); return { items: [{ id: path.includes('/releases') ? 'release-1' : 'deployment-1', summary: 'safe' }] }; }, post: async (path, body) => { calls.push(path); expect(body).toMatchObject({ action: 'canary', reason: 'reviewed' }); return { id: 'deployment-1', state: 'canary' }; } }); await client.list('releases'); await client.list('deployments'); await client.action('deployments', 'deployment-1', { action: 'canary', reason: 'reviewed', idempotencyKey: 'request-1' }); expect(calls).toEqual(['/v1/operator/releases?limit=25', '/v1/operator/deployments?limit=25', '/v1/operator/deployments/deployment-1/actions']); expect(isOperatorActionAllowed('releases', 'canary')).toBe(false); expect(isOperatorActionAllowed('deployments', 'canary')).toBe(true); expect(operatorResources).toHaveLength(16); });
  it('maps certified releases to read-only reads and deployments to stateful controls', async () => { const app = await readFile(new URL('../src/app.ts', import.meta.url), 'utf8'); expect(app).toContain("releases: 'releases'"); expect(app).toContain("deployments: 'deployments'"); expect(app).toContain("if (selected === 'releases') return undefined"); expect(app).toContain("if (selected === 'deployments')"); });
  it('ships a responsive authenticated shell that uses external bearer identity, confirmation, errors and redaction', async () => { const [app, auth, server, css] = await Promise.all([readFile(new URL('../src/app.ts', import.meta.url), 'utf8'), readFile(new URL('../src/platform-auth.ts', import.meta.url), 'utf8'), readFile(new URL('../src/server.ts', import.meta.url), 'utf8'), readFile(new URL('../public/styles.css', import.meta.url), 'utf8')]); expect(auth).toContain('Authorization Code + PKCE'); expect(auth).toContain('testMode'); expect(server).toContain('PRODUCT_API_PUBLIC_ORIGIN'); expect(app).toContain('authorization: `Bearer ${session.accessToken}`'); expect(app).toContain('role="alert"'); expect(app).toContain('showModal'); expect(app).toContain('workflow definitions or credentials'); expect(css).toContain('@media(max-width:700px)'); });
});
