-- WP-08 durable monitoring, incidents, maintenance actions, deployments and pauses.
-- migrate:up

drop index if exists lautowork.uq_lautowork_one_active_deployment_per_instance;
create unique index uq_lautowork_one_active_baseline_per_instance on lautowork.automation_deployments(org_id,instance_id) where state='active';
create unique index uq_lautowork_one_canary_per_instance on lautowork.automation_deployments(org_id,instance_id) where state='canary';

alter table lautowork.automation_alerts
  add column if not exists routing_key text,
  add column if not exists repeat_after timestamptz,
  add column if not exists last_delivered_at timestamptz;
alter table lautowork.automation_health_snapshots add column if not exists details jsonb not null default '{}'::jsonb;

create table lautowork.operation_action_records (
  id uuid primary key, org_id uuid not null references platform.organizations(id) on delete restrict,
  instance_id uuid not null, action_kind text not null check (action_kind in ('retry','pause_instance','fail_over','rollback_certified')),
  actor_ref text not null, reason text not null, evidence_ref text not null, before_state jsonb not null,
  after_state jsonb not null, result text not null check (result in ('succeeded','failed','rejected')),
  error_summary text, compensating_action text not null, created_at timestamptz not null default now(),
  foreign key (instance_id, org_id) references lautowork.automation_instances(id, org_id) on delete restrict
);
create table lautowork.deployment_operation_events (
  id uuid primary key, org_id uuid not null references platform.organizations(id) on delete restrict,
  deployment_id uuid not null, candidate_release_id uuid not null, baseline_release_id uuid not null,
  action text not null check (action in ('canary','promote','rollback')), actor_ref text not null,
  approval_ref text not null, health_evidence_ref text not null, evidence_digest text not null check (evidence_digest ~ '^sha256:[a-f0-9]{64}$'),
  record jsonb not null, created_at timestamptz not null default now(),
  foreign key (deployment_id, org_id) references lautowork.automation_deployments(id, org_id) on delete restrict,
  foreign key (candidate_release_id, org_id) references lautowork.automation_releases(id, org_id) on delete restrict,
  foreign key (baseline_release_id, org_id) references lautowork.automation_releases(id, org_id) on delete restrict
);
create table lautowork.deployment_transitions (
  id uuid primary key default gen_random_uuid(), org_id uuid not null references platform.organizations(id) on delete restrict,
  instance_id uuid not null, deployment_id uuid not null, action text not null check(action in ('canary','promote','rollback')), idempotency_key text not null,
  status text not null check(status in ('prepared','committed','failed','compensation_failed')), authority jsonb not null,
  actor_ref text not null, reason text not null, committed_record jsonb, error_summary text, created_at timestamptz not null default now(), completed_at timestamptz,
  foreign key(instance_id,org_id) references lautowork.automation_instances(id,org_id) on delete restrict, foreign key(deployment_id,org_id) references lautowork.automation_deployments(id,org_id) on delete restrict, unique(org_id,instance_id,idempotency_key), unique(id,org_id)
);
create unique index uq_lautowork_one_prepared_transition_per_instance on lautowork.deployment_transitions(org_id,instance_id) where status='prepared';
create table lautowork.deployment_transition_events (
  id bigserial primary key, org_id uuid not null references platform.organizations(id) on delete restrict,
  transition_id uuid not null, event_type text not null check(event_type in ('prepared','committed','failed','compensation_failed')),
  evidence jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(),
  foreign key(transition_id,org_id) references lautowork.deployment_transitions(id,org_id) on delete restrict
);
create table lautowork.automation_pause_controls (
  id uuid primary key default gen_random_uuid(), org_id uuid not null references platform.organizations(id) on delete restrict,
  scope text not null check (scope in ('global','automation','organisation','instance')), automation_id text, instance_id uuid,
  active boolean not null, actor_ref text not null, reason text not null, evidence_ref text not null, created_at timestamptz not null default now(),
  check ((scope='automation' and automation_id is not null and instance_id is null) or (scope='instance' and instance_id is not null) or (scope in ('global','organisation') and automation_id is null and instance_id is null)),
  foreign key (instance_id, org_id) references lautowork.automation_instances(id, org_id) on delete restrict
);
create table lautowork.alert_delivery_attempts (
  id bigserial primary key, org_id uuid not null references platform.organizations(id) on delete restrict,
  alert_id uuid not null, routing_key text not null, severity text not null, recovered boolean not null,
  created_at timestamptz not null default now(), foreign key (alert_id, org_id) references lautowork.automation_alerts(id, org_id) on delete restrict
);
create table lautowork.operation_retry_outbox (
  id uuid primary key default gen_random_uuid(), org_id uuid not null references platform.organizations(id) on delete restrict,
  instance_id uuid not null, authorization_ref text not null, status text not null default 'pending' check (status in ('pending','delivering','delivered','failed')),
  attempts integer not null default 0, available_at timestamptz not null default now(), delivered_at timestamptz, last_error text, created_at timestamptz not null default now(),
  foreign key (instance_id,org_id) references lautowork.automation_instances(id,org_id) on delete restrict,
  unique(org_id,instance_id,authorization_ref)
);

do $$ declare t text; begin foreach t in array array['operation_action_records','deployment_operation_events','deployment_transitions','deployment_transition_events','automation_pause_controls','alert_delivery_attempts','operation_retry_outbox'] loop
  execute format('alter table lautowork.%I enable row level security', t); execute format('alter table lautowork.%I force row level security', t);
  execute format('create policy %I on lautowork.%I for select to svc_lautowork_runtime, svc_observer using (org_id::text = current_setting(''request.jwt.claim.org_id'', true) and (current_setting(''request.jwt.claim.role'', true) = ''service_role'' or platform.has_org_access(org_id, ''client_viewer'')))', 'lautowork_'||t||'_select', t);
end loop; end $$;
create trigger operation_action_records_append_only before update or delete on lautowork.operation_action_records for each row execute function lautowork.reject_append_only_mutation();
create trigger deployment_operation_events_append_only before update or delete on lautowork.deployment_operation_events for each row execute function lautowork.reject_append_only_mutation();
create trigger deployment_transition_events_append_only before update or delete on lautowork.deployment_transition_events for each row execute function lautowork.reject_append_only_mutation();
create trigger automation_pause_controls_append_only before update or delete on lautowork.automation_pause_controls for each row execute function lautowork.reject_append_only_mutation();
create trigger alert_delivery_attempts_append_only before update or delete on lautowork.alert_delivery_attempts for each row execute function lautowork.reject_append_only_mutation();

create function public.linkautowork_monitor_targets(p_org_id uuid) returns jsonb language plpgsql security definer set search_path=lautowork,pg_temp as $$
declare v jsonb; begin perform lautowork.assert_command_authorized(p_org_id);
select coalesce(jsonb_agg(jsonb_build_object('orgId',i.org_id,'automationId',d.automation_id,'instanceId',i.id,
 'cadenceMs',coalesce((i.configuration->>'cadence_ms')::bigint,86400000),'graceMs',coalesce((i.configuration->>'grace_ms')::bigint,900000),
 'lastExpectedAt',coalesce(i.configuration->>'last_expected_at',i.created_at::text),'enabled',i.state in ('ready','active'),'executions',coalesce(x.rows,'[]'::jsonb))),'[]'::jsonb) into v
from automation_instances i join automation_definitions d on d.id=i.definition_id and d.org_id=i.org_id
left join lateral (select jsonb_agg(jsonb_build_object('executionId',e.id,'status',e.status,'acceptedAt',e.accepted_at,'startedAt',(select min(occurred_at) from automation_execution_events where execution_id=e.id and event_type='started'),'completedAt',e.completed_at,'callbackAt',(select max(created_at) from automation_execution_events where execution_id=e.id),'retryCount',e.retry_count,'failureClass',e.failure_class)) rows from automation_executions e where e.org_id=i.org_id and e.instance_id=i.id) x on true
where i.org_id=p_org_id; return v; end $$;

create function public.linkautowork_write_health(p_record jsonb) returns void language plpgsql security definer set search_path=lautowork,pg_temp as $$ begin
perform lautowork.assert_command_authorized((p_record->>'orgId')::uuid); insert into automation_health_snapshots(org_id,instance_id,health_state,summary_ref,observed_at,details)
values((p_record->>'orgId')::uuid,(p_record->>'instanceId')::uuid,case p_record->>'state' when 'healthy' then 'healthy' when 'unknown' then 'unknown' when 'critical' then 'critical' else 'warning' end,'evidence://monitor/redacted',(p_record->>'observedAt')::timestamptz,p_record); end $$;

create function public.linkautowork_open_alert_incident(p_record jsonb) returns jsonb language plpgsql security definer set search_path=lautowork,pg_temp as $$
declare a automation_alerts%rowtype; iid uuid; deliver boolean:=false; begin perform lautowork.assert_command_authorized((p_record->>'orgId')::uuid);
select * into a from automation_alerts where org_id=(p_record->>'orgId')::uuid and instance_id=(p_record->>'instanceId')::uuid and dedupe_key=p_record->>'routingKey' and status in ('open','acknowledged') order by created_at desc limit 1 for update;
if not found then insert into automation_alerts(org_id,instance_id,dedupe_key,routing_key,severity,status,evidence_ref,repeat_after) values((p_record->>'orgId')::uuid,(p_record->>'instanceId')::uuid,p_record->>'routingKey',p_record->>'routingKey',case when p_record->>'severity'='critical' then 'critical' else 'warning' end,'open',p_record->>'evidenceRef',(p_record->>'repeatAfter')::timestamptz) returning * into a; iid:=gen_random_uuid(); insert into automation_incidents(id,org_id,instance_id,severity,status,incident_key) values(iid,a.org_id,a.instance_id,a.severity,'open','ops-'||replace(a.id::text,'-','')); insert into automation_incident_events(org_id,incident_id,event_type,actor_ref,evidence_ref) values(a.org_id,iid,'opened','monitor',a.evidence_ref); deliver:=true;
else select id into iid from automation_incidents where org_id=a.org_id and incident_key='ops-'||replace(a.id::text,'-',''); if a.repeat_after<=now() then update automation_alerts set repeat_after=(p_record->>'repeatAfter')::timestamptz where id=a.id; deliver:=true; end if; end if;
return jsonb_build_object('alertId',a.id,'incidentId',iid,'deliver',deliver); end $$;

create function public.linkautowork_recover_alert_incident(p_record jsonb) returns jsonb language plpgsql security definer set search_path=lautowork,pg_temp as $$
declare a automation_alerts%rowtype; iid uuid; begin perform lautowork.assert_command_authorized((p_record->>'orgId')::uuid); select * into a from automation_alerts where org_id=(p_record->>'orgId')::uuid and instance_id=(p_record->>'instanceId')::uuid and dedupe_key=p_record->>'routingKey' and status in ('open','acknowledged') limit 1 for update; if not found then return null; end if; update automation_alerts set status='resolved',resolved_at=now(),evidence_ref=p_record->>'evidenceRef' where id=a.id; select id into iid from automation_incidents where org_id=a.org_id and incident_key='ops-'||replace(a.id::text,'-',''); update automation_incidents set status='resolved' where id=iid; insert into automation_incident_events(org_id,incident_id,event_type,actor_ref,evidence_ref) values(a.org_id,iid,'resolved','monitor',p_record->>'evidenceRef'); return jsonb_build_object('alertId',a.id,'deliver',true); end $$;

create function public.linkautowork_health_view(p_org_id uuid) returns jsonb language plpgsql security definer set search_path=lautowork,pg_temp as $$ declare v jsonb; begin perform lautowork.assert_command_authorized(p_org_id); select coalesce(jsonb_agg(details order by observed_at desc),'[]'::jsonb) into v from (select distinct on(instance_id) * from automation_health_snapshots where org_id=p_org_id order by instance_id,observed_at desc) s; return v; end $$;

create function public.linkautowork_transition_incident(p_record jsonb) returns void language plpgsql security definer set search_path=lautowork,pg_temp as $$ declare old_status text; begin perform lautowork.assert_command_authorized((p_record->>'orgId')::uuid); select status into strict old_status from automation_incidents where id=(p_record->>'incidentId')::uuid and org_id=(p_record->>'orgId')::uuid for update; if array_position(array['open','acknowledged','investigating','mitigated','resolved','closed'],p_record->>'status') < array_position(array['open','acknowledged','investigating','mitigated','resolved','closed'],old_status) then raise exception 'incident lifecycle cannot move backward'; end if; update automation_incidents set status=p_record->>'status',closed_at=case when p_record->>'status'='closed' then now() else closed_at end where id=(p_record->>'incidentId')::uuid; insert into automation_incident_events(org_id,incident_id,event_type,actor_ref,evidence_ref) values((p_record->>'orgId')::uuid,(p_record->>'incidentId')::uuid,p_record->>'status',p_record->>'actor',p_record->>'evidenceRef'); end $$;

create function public.linkautowork_record_alert_delivery(p_record jsonb) returns void language plpgsql security definer set search_path=lautowork,pg_temp as $$ begin perform lautowork.assert_command_authorized((p_record->>'orgId')::uuid); insert into alert_delivery_attempts(org_id,alert_id,routing_key,severity,recovered) values((p_record->>'orgId')::uuid,(p_record->>'alertId')::uuid,p_record->>'routingKey',p_record->>'severity',(p_record->>'recovered')::boolean); update automation_alerts set last_delivered_at=now() where id=(p_record->>'alertId')::uuid and org_id=(p_record->>'orgId')::uuid; end $$;
create function public.linkautowork_record_operation_action(p_record jsonb) returns void language plpgsql security definer set search_path=lautowork,pg_temp as $$ begin perform lautowork.assert_command_authorized((p_record->>'orgId')::uuid); insert into operation_action_records(id,org_id,instance_id,action_kind,actor_ref,reason,evidence_ref,before_state,after_state,result,error_summary,compensating_action) values((p_record->>'id')::uuid,(p_record->>'orgId')::uuid,(p_record->>'instanceId')::uuid,p_record->>'kind',p_record->>'actor',p_record->>'reason',p_record->>'evidenceRef',p_record->'before',p_record->'after',p_record->>'result',p_record->>'error',p_record->>'compensatingAction'); end $$;
create function public.linkautowork_record_deployment_event(p_record jsonb) returns void language plpgsql security definer set search_path=lautowork,pg_temp as $$ declare authority jsonb; begin perform lautowork.assert_command_authorized((p_record->>'orgId')::uuid); authority:=public.linkautowork_deployment_authority((p_record->>'orgId')::uuid,(p_record->>'deploymentId')::uuid); if not (authority->>'baselineCertified')::boolean or authority->>'approvalRef' is null or authority->>'healthEvidenceRef' is null then raise exception 'durable deployment approval and health evidence required'; end if; insert into deployment_operation_events(id,org_id,deployment_id,candidate_release_id,baseline_release_id,action,actor_ref,approval_ref,health_evidence_ref,evidence_digest,record) values((p_record->>'id')::uuid,(p_record->>'orgId')::uuid,(p_record->>'deploymentId')::uuid,(authority->>'candidateReleaseId')::uuid,(authority->>'baselineReleaseId')::uuid,p_record->>'action',p_record->>'actor',authority->>'approvalRef',authority->>'healthEvidenceRef',p_record->>'evidenceDigest',p_record||jsonb_build_object('durableAuthority',authority)); end $$;
create function public.linkautowork_write_pause(p_record jsonb) returns void language plpgsql security definer set search_path=lautowork,pg_temp as $$ begin perform lautowork.assert_command_authorized((p_record->>'orgId')::uuid); insert into automation_pause_controls(org_id,scope,automation_id,instance_id,active,actor_ref,reason,evidence_ref) values((p_record->>'orgId')::uuid,p_record->>'scope',p_record->>'automationId',(p_record->>'instanceId')::uuid,(p_record->>'active')::boolean,p_record->>'actor',p_record->>'reason',p_record->>'evidenceRef'); end $$;

create function public.linkautowork_active_pause(p_org_id uuid,p_automation_id text,p_instance_id uuid) returns jsonb language plpgsql security definer set search_path=lautowork,pg_temp as $$ declare result jsonb; begin perform lautowork.assert_command_authorized(p_org_id);
select jsonb_build_object('scope',scope,'reason',reason) into result from (
 select distinct on(scope,coalesce(automation_id,''),coalesce(instance_id,'00000000-0000-0000-0000-000000000000'::uuid)) scope,automation_id,instance_id,active,reason,created_at
 from automation_pause_controls where org_id=p_org_id and (scope in ('global','organisation') or scope='automation' and automation_id=p_automation_id or scope='instance' and instance_id=p_instance_id)
 order by scope,coalesce(automation_id,''),coalesce(instance_id,'00000000-0000-0000-0000-000000000000'::uuid),created_at desc
) latest where active order by case scope when 'global' then 1 when 'automation' then 2 when 'organisation' then 3 else 4 end limit 1; return result; end $$;

create function public.linkautowork_run_maintenance_checks(p_org_id uuid) returns jsonb language plpgsql security definer set search_path=lautowork,pg_temp as $$ declare result jsonb; begin perform lautowork.assert_command_authorized(p_org_id);
select coalesce(jsonb_agg(jsonb_build_object('instanceId',i.id,'findings',to_jsonb(array_remove(array[
 case when i.state='paused' then 'disabled_workflow' end,
 case when r.workflow_digest is distinct from d.workflow_digest then 'version_drift' end,
 case when exists(select 1 from automation_secret_bindings s where s.org_id=i.org_id and s.instance_id=i.id and s.health_state in ('expiring','invalid','revoked')) then 'credential_attention' end,
 case when not exists(select 1 from automation_eval_runs er where er.org_id=i.org_id and er.release_id=i.release_id and er.status='passed') then 'untested_dependency' end,
 case when exists(select 1 from automation_incidents inc where inc.org_id=i.org_id and inc.instance_id=i.id and inc.status not in ('resolved','closed')) then 'unresolved_incident' end
],null)))),'[]'::jsonb) into result from automation_instances i join automation_releases r on r.id=i.release_id and r.org_id=i.org_id left join lateral (select workflow_digest from automation_deployments where org_id=i.org_id and instance_id=i.id order by created_at desc limit 1) d on true where i.org_id=p_org_id; return result; end $$;

create function public.linkautowork_authorize_operation_action(p_org_id uuid,p_instance_id uuid,p_action_kind text,p_evidence_ref text) returns jsonb language plpgsql security definer set search_path=lautowork,pg_temp as $$ declare cfg jsonb; current_workflow text; baseline_workflow text; supported boolean; approved boolean; begin perform lautowork.assert_command_authorized(p_org_id); select configuration into strict cfg from automation_instances where id=p_instance_id and org_id=p_org_id; supported:=coalesce(cfg->'remediation_allowlist','[]'::jsonb) ? p_action_kind; select exists(select 1 from approval_requests ar join approval_decisions ad on ad.approval_request_id=ar.id and ad.org_id=ar.org_id where ar.org_id=p_org_id and ar.subject_id=p_instance_id and ar.subject_type='maintenance' and ar.status='approved' and ad.decision='approved' and ad.evidence_ref=p_evidence_ref) into approved; select n8n_workflow_id into current_workflow from automation_deployments where org_id=p_org_id and instance_id=p_instance_id and state in ('active','canary') order by created_at desc limit 1; select d.n8n_workflow_id into baseline_workflow from automation_deployments d join automation_releases r on r.id=d.release_id and r.org_id=d.org_id where d.org_id=p_org_id and d.instance_id=p_instance_id and r.lifecycle='certified' and d.n8n_workflow_id is distinct from current_workflow order by d.created_at desc limit 1; return jsonb_build_object('allowed',supported and approved,'supportsFailover',coalesce((cfg->>'supports_failover')::boolean,false),'authorizationRef',case when approved then p_evidence_ref end,'currentWorkflowId',current_workflow,'baselineWorkflowId',baseline_workflow); end $$;

create function public.linkautowork_deployment_authority(p_org_id uuid,p_deployment_id uuid) returns jsonb language plpgsql security definer set search_path=lautowork,pg_temp as $$ declare d automation_deployments%rowtype; baseline automation_deployments%rowtype; cfg jsonb; approval_ref text; health_ref text; samples int; successes int; begin perform lautowork.assert_command_authorized(p_org_id); select * into strict d from automation_deployments where id=p_deployment_id and org_id=p_org_id; select bd.* into baseline from automation_deployments bd join automation_releases br on br.id=bd.release_id and br.org_id=bd.org_id where bd.org_id=p_org_id and bd.instance_id=d.instance_id and bd.id<>d.id and br.lifecycle='certified' order by bd.created_at desc limit 1; if baseline.id is null then raise exception 'certified baseline deployment not found'; end if; select configuration into cfg from automation_instances where id=d.instance_id and org_id=p_org_id; select ad.evidence_ref into approval_ref from approval_requests ar join approval_decisions ad on ad.approval_request_id=ar.id and ad.org_id=ar.org_id where ar.org_id=p_org_id and ar.subject_type='deployment' and ar.subject_id=d.id and ar.status='approved' and ad.decision='approved' order by ad.created_at desc limit 1; select summary_ref into health_ref from automation_health_snapshots where org_id=p_org_id and instance_id=d.instance_id and health_state='healthy' and observed_at>=d.created_at order by observed_at desc limit 1; select count(*),count(*) filter(where status='succeeded') into samples,successes from automation_executions where org_id=p_org_id and deployment_id=d.id and completed_at is not null; return jsonb_build_object('baselineDeploymentId',baseline.id,'candidateReleaseId',d.release_id,'baselineReleaseId',baseline.release_id,'candidateWorkflowId',d.n8n_workflow_id,'baselineWorkflowId',baseline.n8n_workflow_id,'compatibleBindings',d.configuration_digest=(select configuration_digest from automation_instances where id=d.instance_id and org_id=p_org_id) and exists(select 1 from automation_bindings where org_id=p_org_id and instance_id=d.instance_id and enabled),'candidateCertified',exists(select 1 from automation_releases where id=d.release_id and org_id=p_org_id and lifecycle='certified'),'baselineCertified',true,'approvalRef',approval_ref,'healthEvidenceRef',health_ref,'sampleCount',samples,'minimumSamples',coalesce((cfg->>'canary_min_samples')::int,5),'elapsedMs',(extract(epoch from(now()-d.created_at))*1000)::bigint,'minimumWindowMs',coalesce((cfg->>'canary_min_window_ms')::bigint,3600000),'candidateSuccessRate',case when samples=0 then 0 else successes::numeric/samples end,'baselineSuccessRate',coalesce((select avg(case when status='succeeded' then 1 else 0 end) from automation_executions where org_id=p_org_id and deployment_id=baseline.id and completed_at is not null),1)); end $$;

create or replace function public.linkautowork_deployment_authority(p_org_id uuid,p_deployment_id uuid) returns jsonb language plpgsql security definer set search_path=lautowork,pg_temp as $$ declare d automation_deployments%rowtype; baseline automation_deployments%rowtype; cfg jsonb; approval_ref text; health_ref text; samples int; successes int; begin perform lautowork.assert_command_authorized(p_org_id); select * into strict d from automation_deployments where id=p_deployment_id and org_id=p_org_id; select bd.* into baseline from automation_deployments bd join automation_releases br on br.id=bd.release_id and br.org_id=bd.org_id where bd.org_id=p_org_id and bd.instance_id=d.instance_id and bd.id<>d.id and br.lifecycle='certified' and ((d.state='active' and bd.state='rolled_back') or (d.state<>'active' and bd.state='active')) order by bd.created_at desc limit 1; if baseline.id is null then raise exception 'certified baseline deployment not found'; end if; select configuration into cfg from automation_instances where id=d.instance_id and org_id=p_org_id; select ad.evidence_ref into approval_ref from approval_requests ar join approval_decisions ad on ad.approval_request_id=ar.id and ad.org_id=ar.org_id where ar.org_id=p_org_id and ar.subject_type='deployment' and ar.subject_id=d.id and ar.status='approved' and ad.decision='approved' order by ad.created_at desc limit 1; select summary_ref into health_ref from automation_health_snapshots where org_id=p_org_id and instance_id=d.instance_id and health_state='healthy' and observed_at>=d.created_at order by observed_at desc limit 1; select count(*),count(*) filter(where status='succeeded') into samples,successes from automation_executions where org_id=p_org_id and deployment_id=d.id and completed_at is not null; return jsonb_build_object('baselineDeploymentId',baseline.id,'candidateReleaseId',d.release_id,'baselineReleaseId',baseline.release_id,'candidateWorkflowId',d.n8n_workflow_id,'baselineWorkflowId',baseline.n8n_workflow_id,'compatibleBindings',d.configuration_digest=(select configuration_digest from automation_instances where id=d.instance_id and org_id=p_org_id) and exists(select 1 from automation_bindings where org_id=p_org_id and instance_id=d.instance_id and enabled),'candidateCertified',exists(select 1 from automation_releases where id=d.release_id and org_id=p_org_id and lifecycle='certified'),'baselineCertified',true,'approvalRef',approval_ref,'healthEvidenceRef',health_ref,'sampleCount',samples,'minimumSamples',coalesce((cfg->>'canary_min_samples')::int,5),'elapsedMs',(extract(epoch from(now()-d.created_at))*1000)::bigint,'minimumWindowMs',coalesce((cfg->>'canary_min_window_ms')::bigint,3600000),'candidateSuccessRate',case when samples=0 then 0 else successes::numeric/samples end,'baselineSuccessRate',coalesce((select avg(case when status='succeeded' then 1 else 0 end) from automation_executions where org_id=p_org_id and deployment_id=baseline.id and completed_at is not null),1)); end $$;

create function public.linkautowork_prepare_deployment_transition(p_record jsonb) returns jsonb language plpgsql security definer set search_path=lautowork,pg_temp as $$ declare prior deployment_transitions%rowtype; authority jsonb; tid uuid; target_instance_id uuid; target_org uuid:=(p_record->>'orgId')::uuid; target_deployment uuid:=(p_record->>'deploymentId')::uuid; begin perform lautowork.assert_command_authorized(target_org); select instance_id into strict target_instance_id from automation_deployments where id=target_deployment and org_id=target_org; perform pg_advisory_xact_lock(hashtextextended(target_org::text||':'||target_instance_id::text,0)); select * into prior from deployment_transitions where org_id=target_org and instance_id=target_instance_id and idempotency_key=p_record->>'idempotencyKey'; if prior.id is not null then return jsonb_build_object('transitionId',prior.id,'disposition',case when prior.status='committed' then 'replay' else 'in_progress' end,'authority',prior.authority,'committedRecord',prior.committed_record); end if; select * into prior from deployment_transitions where org_id=target_org and instance_id=target_instance_id and status='prepared' limit 1; if prior.id is not null then return jsonb_build_object('transitionId',prior.id,'disposition','in_progress','authority',prior.authority); end if; authority:=public.linkautowork_deployment_authority(target_org,target_deployment); insert into deployment_transitions(org_id,instance_id,deployment_id,action,idempotency_key,status,authority,actor_ref,reason) values(target_org,target_instance_id,target_deployment,p_record->>'action',p_record->>'idempotencyKey','prepared',authority,p_record->>'actor',p_record->>'reason') returning id into tid; insert into deployment_transition_events(org_id,transition_id,event_type,evidence) values(target_org,tid,'prepared',authority); return jsonb_build_object('transitionId',tid,'disposition','prepared','authority',authority); end $$;

create or replace function public.linkautowork_resolve_bound_instance(p_org_id uuid,p_consumer_system text,p_operation text) returns jsonb language plpgsql security definer set search_path=lautowork,pg_temp as $$ declare result jsonb; begin perform lautowork.assert_command_authorized(p_org_id); select jsonb_build_object('bindingId',b.id,'orgId',b.org_id,'automationId',def.automation_id,'instanceId',i.id,'consumerSystem',b.consumer_system,'operation',b.binding_operation,'enabled',b.enabled,'instanceState',i.state,'releaseId',r.id,'releaseLifecycle',r.lifecycle,'deploymentId',active_d.id,'workflowId',active_d.n8n_workflow_id,'workflowDigest',r.workflow_digest,'deployedDigest',active_d.workflow_digest,'configurationDigest',i.configuration_digest,'deployedConfigurationDigest',active_d.configuration_digest,'webhookPath',coalesce(i.configuration->>'webhook_path','/instance/'||i.id::text),'method',coalesce(i.configuration->>'webhook_method','POST'),'criticality',coalesce(i.configuration->>'criticality','non_critical'),'timeoutMs',coalesce((i.configuration->>'timeout_ms')::integer,30000),'retryCount',coalesce((i.configuration->>'retry_count')::integer,0),'inputSchema',coalesce(i.configuration->'input_schema','{"type":"object","additionalProperties":false}'::jsonb),'secretRefs',coalesce((select jsonb_agg(s.secret_ref order by s.secret_ref) from automation_secret_bindings s where s.org_id=i.org_id and s.instance_id=i.id and s.required),'[]'::jsonb),'canaryDeploymentId',canary_d.id,'canaryWorkflowId',canary_d.n8n_workflow_id) into result from automation_bindings b join automation_instances i on i.id=b.instance_id and i.org_id=b.org_id join automation_releases r on r.id=i.release_id and r.org_id=i.org_id join automation_definitions def on def.id=i.definition_id and def.org_id=i.org_id join automation_deployments active_d on active_d.instance_id=i.id and active_d.org_id=i.org_id and active_d.state='active' left join automation_deployments canary_d on canary_d.instance_id=i.id and canary_d.org_id=i.org_id and canary_d.state='canary' where b.org_id=p_org_id and b.consumer_system=p_consumer_system and b.binding_operation=p_operation and b.enabled; return result; end $$;

create function public.linkautowork_commit_deployment_transition(p_org_id uuid,p_transition_id uuid,p_record jsonb) returns void language plpgsql security definer set search_path=lautowork,pg_temp as $$ declare t deployment_transitions%rowtype; baseline_id uuid; begin perform lautowork.assert_command_authorized(p_org_id); select * into strict t from deployment_transitions where id=p_transition_id and org_id=p_org_id for update; if t.status='committed' then return; end if; if t.status<>'prepared' then raise exception 'deployment transition is not prepared'; end if; if t.authority->>'approvalRef' is null or t.authority->>'healthEvidenceRef' is null or not (t.authority->>'baselineCertified')::boolean then raise exception 'durable deployment authority is incomplete'; end if; if t.action='promote' and (not (t.authority->>'candidateCertified')::boolean or not (t.authority->>'compatibleBindings')::boolean or (t.authority->>'sampleCount')::int<(t.authority->>'minimumSamples')::int or (t.authority->>'elapsedMs')::bigint<(t.authority->>'minimumWindowMs')::bigint or (t.authority->>'candidateSuccessRate')::numeric<(t.authority->>'baselineSuccessRate')::numeric) then raise exception 'durable promotion evidence is insufficient'; end if; baseline_id:=(t.authority->>'baselineDeploymentId')::uuid; if t.action='canary' then update automation_deployments set state='canary' where id=t.deployment_id and org_id=p_org_id; elsif t.action='promote' then update automation_deployments set state='rolled_back' where id=baseline_id and org_id=p_org_id; update automation_deployments set state='active' where id=t.deployment_id and org_id=p_org_id; else update automation_deployments set state='rolled_back' where id=t.deployment_id and org_id=p_org_id; update automation_deployments set state='active' where id=baseline_id and org_id=p_org_id; end if; insert into deployment_operation_events(id,org_id,deployment_id,candidate_release_id,baseline_release_id,action,actor_ref,approval_ref,health_evidence_ref,evidence_digest,record) values((p_record->>'id')::uuid,p_org_id,t.deployment_id,(t.authority->>'candidateReleaseId')::uuid,(t.authority->>'baselineReleaseId')::uuid,t.action,t.actor_ref,t.authority->>'approvalRef',t.authority->>'healthEvidenceRef',p_record->>'evidenceDigest',p_record); update deployment_transitions set status='committed',committed_record=p_record,completed_at=now() where id=t.id; insert into deployment_transition_events(org_id,transition_id,event_type,evidence) values(p_org_id,t.id,'committed',p_record); end $$;

create function public.linkautowork_fail_deployment_transition(p_org_id uuid,p_transition_id uuid,p_error text,p_compensation_failed boolean) returns void language plpgsql security definer set search_path=lautowork,pg_temp as $$ declare t deployment_transitions%rowtype; iid uuid; target_instance_id uuid; begin perform lautowork.assert_command_authorized(p_org_id); select * into strict t from deployment_transitions where id=p_transition_id and org_id=p_org_id for update; if t.status='committed' then raise exception 'committed transition cannot fail'; end if; update deployment_transitions set status=case when p_compensation_failed then 'compensation_failed' else 'failed' end,error_summary=left(p_error,1000),completed_at=now() where id=t.id; insert into deployment_transition_events(org_id,transition_id,event_type,evidence) values(p_org_id,t.id,case when p_compensation_failed then 'compensation_failed' else 'failed' end,jsonb_build_object('error',left(p_error,1000))); if p_compensation_failed then select d.instance_id into target_instance_id from automation_deployments d where d.id=t.deployment_id and d.org_id=p_org_id; iid:=gen_random_uuid(); insert into automation_incidents(id,org_id,instance_id,deployment_id,severity,status,incident_key) values(iid,p_org_id,target_instance_id,t.deployment_id,'critical','open','deployment-compensation-'||replace(t.id::text,'-','')); insert into automation_incident_events(org_id,incident_id,event_type,actor_ref,evidence_ref) values(p_org_id,iid,'opened','deployment-transition','evidence://deployment/compensation-failed'); end if; end $$;

create function public.linkautowork_execute_retry(p_org_id uuid,p_instance_id uuid,p_authorization_ref text) returns jsonb language plpgsql security definer set search_path=lautowork,pg_temp as $$ declare auth jsonb; oid uuid; begin perform lautowork.assert_command_authorized(p_org_id); auth:=public.linkautowork_authorize_operation_action(p_org_id,p_instance_id,'retry',p_authorization_ref); if not (auth->>'allowed')::boolean then raise exception 'retry is not durably approved'; end if; insert into operation_retry_outbox(org_id,instance_id,authorization_ref) values(p_org_id,p_instance_id,p_authorization_ref) on conflict(org_id,instance_id,authorization_ref) do update set available_at=least(operation_retry_outbox.available_at,excluded.available_at) returning id into oid; return jsonb_build_object('queued',true,'outboxId',oid,'instanceId',p_instance_id); end $$;
create function public.linkautowork_claim_retry(p_org_id uuid) returns jsonb language plpgsql security definer set search_path=lautowork,pg_temp as $$ declare q operation_retry_outbox%rowtype; cfg jsonb; begin perform lautowork.assert_command_authorized(p_org_id); select * into q from operation_retry_outbox where org_id=p_org_id and status in ('pending','failed') and available_at<=now() order by created_at for update skip locked limit 1; if q.id is null then return null; end if; select configuration into cfg from automation_instances where id=q.instance_id and org_id=q.org_id; update operation_retry_outbox set status='delivering',attempts=attempts+1 where id=q.id; return jsonb_build_object('id',q.id,'orgId',q.org_id,'instanceId',q.instance_id,'authorizationRef',q.authorization_ref,'webhookPath',coalesce(cfg->>'webhook_path','/instance/'||q.instance_id::text),'method',coalesce(cfg->>'webhook_method','POST')); end $$;
create function public.linkautowork_complete_retry(p_org_id uuid,p_outbox_id uuid,p_delivered boolean,p_error text default null) returns void language plpgsql security definer set search_path=lautowork,pg_temp as $$ begin perform lautowork.assert_command_authorized(p_org_id); update operation_retry_outbox set status=case when p_delivered then 'delivered' else 'failed' end,delivered_at=case when p_delivered then now() end,last_error=case when p_delivered then null else left(p_error,500) end,available_at=case when p_delivered then available_at else now()+interval '5 minutes' end where id=p_outbox_id and org_id=p_org_id and status='delivering'; if not found then raise exception 'retry delivery lease not found'; end if; end $$;
create function public.linkautowork_execute_instance_pause(p_org_id uuid,p_instance_id uuid,p_authorization_ref text) returns jsonb language plpgsql security definer set search_path=lautowork,pg_temp as $$ declare auth jsonb; begin perform lautowork.assert_command_authorized(p_org_id); auth:=public.linkautowork_authorize_operation_action(p_org_id,p_instance_id,'pause_instance',p_authorization_ref); if not (auth->>'allowed')::boolean then raise exception 'pause is not durably approved'; end if; update automation_instances set state='paused',updated_at=now() where id=p_instance_id and org_id=p_org_id; return jsonb_build_object('state','paused','instanceId',p_instance_id); end $$;
create function public.linkautowork_execute_failover(p_org_id uuid,p_instance_id uuid,p_authorization_ref text) returns jsonb language plpgsql security definer set search_path=lautowork,pg_temp as $$ declare auth jsonb; begin perform lautowork.assert_command_authorized(p_org_id); auth:=public.linkautowork_authorize_operation_action(p_org_id,p_instance_id,'fail_over',p_authorization_ref); if not (auth->>'allowed')::boolean or not (auth->>'supportsFailover')::boolean then raise exception 'failover is not durably approved and supported'; end if; return jsonb_build_object('switched',true); end $$;
create function public.linkautowork_execute_rollback(p_org_id uuid,p_instance_id uuid,p_authorization_ref text) returns jsonb language plpgsql security definer set search_path=lautowork,pg_temp as $$ declare auth jsonb; current_id uuid; baseline_id uuid; begin perform lautowork.assert_command_authorized(p_org_id); auth:=public.linkautowork_authorize_operation_action(p_org_id,p_instance_id,'rollback_certified',p_authorization_ref); if not (auth->>'allowed')::boolean then raise exception 'rollback is not durably approved'; end if; select id into current_id from automation_deployments where org_id=p_org_id and instance_id=p_instance_id and state in ('active','canary') order by created_at desc limit 1; select d.id into baseline_id from automation_deployments d join automation_releases r on r.id=d.release_id and r.org_id=d.org_id where d.org_id=p_org_id and d.instance_id=p_instance_id and r.lifecycle='certified' and d.id is distinct from current_id order by d.created_at desc limit 1; if baseline_id is null then raise exception 'no certified rollback deployment'; end if; update automation_deployments set state='rolled_back' where id=current_id; update automation_deployments set state='active' where id=baseline_id; return jsonb_build_object('rolledBackDeploymentId',current_id,'activeDeploymentId',baseline_id); end $$;

do $$ declare f record; role_name text; begin for f in select p.oid::regprocedure sig from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('linkautowork_monitor_targets','linkautowork_write_health','linkautowork_open_alert_incident','linkautowork_recover_alert_incident','linkautowork_health_view','linkautowork_transition_incident','linkautowork_record_alert_delivery','linkautowork_record_operation_action','linkautowork_record_deployment_event','linkautowork_write_pause','linkautowork_active_pause','linkautowork_run_maintenance_checks','linkautowork_authorize_operation_action','linkautowork_deployment_authority','linkautowork_prepare_deployment_transition','linkautowork_commit_deployment_transition','linkautowork_fail_deployment_transition','linkautowork_execute_retry','linkautowork_claim_retry','linkautowork_complete_retry','linkautowork_execute_instance_pause','linkautowork_execute_failover','linkautowork_execute_rollback') loop execute format('revoke all on function %s from public',f.sig); foreach role_name in array array['service_role','svc_lautowork_runtime'] loop execute format('grant execute on function %s to %I',f.sig,role_name); end loop; end loop; end $$;

-- migrate:down
drop function if exists public.linkautowork_execute_rollback(uuid,uuid,text); drop function if exists public.linkautowork_execute_failover(uuid,uuid,text); drop function if exists public.linkautowork_execute_instance_pause(uuid,uuid,text); drop function if exists public.linkautowork_complete_retry(uuid,uuid,boolean,text); drop function if exists public.linkautowork_claim_retry(uuid); drop function if exists public.linkautowork_execute_retry(uuid,uuid,text); drop function if exists public.linkautowork_fail_deployment_transition(uuid,uuid,text,boolean); drop function if exists public.linkautowork_commit_deployment_transition(uuid,uuid,jsonb); drop function if exists public.linkautowork_prepare_deployment_transition(jsonb); drop function if exists public.linkautowork_deployment_authority(uuid,uuid); drop function if exists public.linkautowork_authorize_operation_action(uuid,uuid,text,text);
drop function if exists public.linkautowork_run_maintenance_checks(uuid); drop function if exists public.linkautowork_active_pause(uuid,text,uuid); drop function if exists public.linkautowork_write_pause(jsonb); drop function if exists public.linkautowork_record_deployment_event(jsonb); drop function if exists public.linkautowork_record_operation_action(jsonb); drop function if exists public.linkautowork_record_alert_delivery(jsonb); drop function if exists public.linkautowork_transition_incident(jsonb); drop function if exists public.linkautowork_health_view(uuid); drop function if exists public.linkautowork_recover_alert_incident(jsonb); drop function if exists public.linkautowork_open_alert_incident(jsonb); drop function if exists public.linkautowork_write_health(jsonb); drop function if exists public.linkautowork_monitor_targets(uuid);
drop table if exists lautowork.operation_retry_outbox; drop table if exists lautowork.alert_delivery_attempts; drop table if exists lautowork.automation_pause_controls; drop table if exists lautowork.deployment_transition_events; drop table if exists lautowork.deployment_transitions; drop table if exists lautowork.deployment_operation_events; drop table if exists lautowork.operation_action_records;
drop index if exists lautowork.uq_lautowork_one_canary_per_instance;
drop index if exists lautowork.uq_lautowork_one_active_baseline_per_instance;
create unique index if not exists uq_lautowork_one_active_deployment_per_instance on lautowork.automation_deployments(org_id,instance_id) where state in ('active','canary');
